//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 SugarWalker.g 2013-04-28 20:05:15

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


	using System;
	using System.Collections;
	using System.Linq;


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;
using Antlr.Runtime.Tree;
using RewriteRuleITokenStream = Antlr.Runtime.Tree.RewriteRuleTokenStream;

namespace  SugarCpp.Compiler 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class SugarWalker : Antlr.Runtime.Tree.TreeParser
{
	internal static readonly string[] tokenNames = new string[] {
		"<invalid>", "<EOR>", "<DOWN>", "<UP>", "Block", "DEDENT", "EXPONENT", "Expr_Alloc", "Expr_Alloc_Auto", "Expr_Bin", "Expr_Block", "Expr_Call", "Expr_Cond", "Expr_Dict", "Expr_Dot", "Expr_Match_Tuple", "Expr_New", "Expr_Prefix", "Expr_Return", "Expr_Suffix", "Expr_Tuple", "Func_Def", "IDENT", "INDENT", "INT", "Left_Bracket", "NEWLINE", "Right_Bracket", "Root", "SP", "STRING", "Stmt_If", "Stmt_While", "Type_Tuple", "'!'", "'%'", "'('", "')'", "'*'", "'+'", "'++'", "','", "'-'", "'--'", "'.'", "'/'", "'<'", "'='", "'>'", "'['", "']'", "'return'", "'|'", "'~'", "DOUBLE", "';'"
	};
	public const int EOF=-1;
	public const int T__34=34;
	public const int T__35=35;
	public const int T__36=36;
	public const int T__37=37;
	public const int T__38=38;
	public const int T__39=39;
	public const int T__40=40;
	public const int T__41=41;
	public const int T__42=42;
	public const int T__43=43;
	public const int T__44=44;
	public const int T__45=45;
	public const int T__46=46;
	public const int T__47=47;
	public const int T__48=48;
	public const int T__49=49;
	public const int T__50=50;
	public const int T__51=51;
	public const int T__52=52;
	public const int T__53=53;
	public const int Block=4;
	public const int DEDENT=5;
	public const int EXPONENT=6;
	public const int Expr_Alloc=7;
	public const int Expr_Alloc_Auto=8;
	public const int Expr_Bin=9;
	public const int Expr_Block=10;
	public const int Expr_Call=11;
	public const int Expr_Cond=12;
	public const int Expr_Dict=13;
	public const int Expr_Dot=14;
	public const int Expr_Match_Tuple=15;
	public const int Expr_New=16;
	public const int Expr_Prefix=17;
	public const int Expr_Return=18;
	public const int Expr_Suffix=19;
	public const int Expr_Tuple=20;
	public const int Func_Def=21;
	public const int IDENT=22;
	public const int INDENT=23;
	public const int INT=24;
	public const int Left_Bracket=25;
	public const int NEWLINE=26;
	public const int Right_Bracket=27;
	public const int Root=28;
	public const int SP=29;
	public const int STRING=30;
	public const int Stmt_If=31;
	public const int Stmt_While=32;
	public const int Type_Tuple=33;
	public const int T__55=55;
	public const int DOUBLE=54;

	public SugarWalker(ITreeNodeStream input)
		: this(input, new RecognizerSharedState())
	{
	}
	public SugarWalker(ITreeNodeStream input, RecognizerSharedState state)
		: base(input, state)
	{
		OnCreated();
	}

	public override string[] TokenNames { get { return SugarWalker.tokenNames; } }
	public override string GrammarFileName { get { return "SugarWalker.g"; } }




	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	#region Rules
	partial void EnterRule_root();
	partial void LeaveRule_root();

	// $ANTLR start "root"
	// SugarWalker.g:23:8: public root returns [Root value] : (a= node ( NEWLINE )* )+ ;
	[GrammarRule("root")]
	public Root root()
	{
		EnterRule_root();
		EnterRule("root", 1);
		TraceIn("root", 1);
		Root value = default(Root);


		AstNode a = default(AstNode);


			value = new Root();

		try { DebugEnterRule(GrammarFileName, "root");
		DebugLocation(23, 1);
		try
		{
			// SugarWalker.g:28:2: ( (a= node ( NEWLINE )* )+ )
			DebugEnterAlt(1);
			// SugarWalker.g:28:4: (a= node ( NEWLINE )* )+
			{
			DebugLocation(28, 4);
			// SugarWalker.g:28:4: (a= node ( NEWLINE )* )+
			int cnt2=0;
			try { DebugEnterSubRule(2);
			while (true)
			{
				int alt2=2;
				try { DebugEnterDecision(2, false);
				int LA2_0 = input.LA(1);

				if ((LA2_0==IDENT||LA2_0==Type_Tuple))
				{
					alt2 = 1;
				}


				} finally { DebugExitDecision(2); }
				switch (alt2)
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:28:5: a= node ( NEWLINE )*
					{
					DebugLocation(28, 7);
					PushFollow(Follow._node_in_root85);
					a=node();
					PopFollow();

					DebugLocation(28, 15);
					 value.List.Add(a); 
					DebugLocation(28, 39);
					// SugarWalker.g:28:39: ( NEWLINE )*
					try { DebugEnterSubRule(1);
					while (true)
					{
						int alt1=2;
						try { DebugEnterDecision(1, false);
						int LA1_0 = input.LA(1);

						if ((LA1_0==NEWLINE))
						{
							alt1 = 1;
						}


						} finally { DebugExitDecision(1); }
						switch ( alt1 )
						{
						case 1:
							DebugEnterAlt(1);
							// SugarWalker.g:28:39: NEWLINE
							{
							DebugLocation(28, 39);
							Match(input,NEWLINE,Follow._NEWLINE_in_root90); 

							}
							break;

						default:
							goto loop1;
						}
					}

					loop1:
						;

					} finally { DebugExitSubRule(1); }


					}
					break;

				default:
					if (cnt2 >= 1)
						goto loop2;

					EarlyExitException eee2 = new EarlyExitException( 2, input );
					DebugRecognitionException(eee2);
					throw eee2;
				}
				cnt2++;
			}
			loop2:
				;

			} finally { DebugExitSubRule(2); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("root", 1);
			LeaveRule("root", 1);
			LeaveRule_root();
		}
		DebugLocation(29, 1);
		} finally { DebugExitRule(GrammarFileName, "root"); }
		return value;

	}
	// $ANTLR end "root"

	partial void EnterRule_node();
	partial void LeaveRule_node();

	// $ANTLR start "node"
	// SugarWalker.g:31:1: node returns [AstNode value] : a= func_def ;
	[GrammarRule("node")]
	private AstNode node()
	{
		EnterRule_node();
		EnterRule("node", 2);
		TraceIn("node", 2);
		AstNode value = default(AstNode);


		FuncDef a = default(FuncDef);

		try { DebugEnterRule(GrammarFileName, "node");
		DebugLocation(31, 1);
		try
		{
			// SugarWalker.g:32:2: (a= func_def )
			DebugEnterAlt(1);
			// SugarWalker.g:32:4: a= func_def
			{
			DebugLocation(32, 6);
			PushFollow(Follow._func_def_in_node112);
			a=func_def();
			PopFollow();

			DebugLocation(32, 17);
			 value = a; 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("node", 2);
			LeaveRule("node", 2);
			LeaveRule_node();
		}
		DebugLocation(33, 1);
		} finally { DebugExitRule(GrammarFileName, "node"); }
		return value;

	}
	// $ANTLR end "node"

	partial void EnterRule_type_name();
	partial void LeaveRule_type_name();

	// $ANTLR start "type_name"
	// SugarWalker.g:35:1: type_name returns [string value] : (a= IDENT ( '<' b= type_name ( ',' b= type_name )* '>' )* ( '*' )* | ^( Type_Tuple (b= type_name )+ ) );
	[GrammarRule("type_name")]
	private string type_name()
	{
		EnterRule_type_name();
		EnterRule("type_name", 3);
		TraceIn("type_name", 3);
		string value = default(string);


		CommonTree a = default(CommonTree);
		string b = default(string);


			value = "";

		try { DebugEnterRule(GrammarFileName, "type_name");
		DebugLocation(35, 1);
		try
		{
			// SugarWalker.g:40:2: (a= IDENT ( '<' b= type_name ( ',' b= type_name )* '>' )* ( '*' )* | ^( Type_Tuple (b= type_name )+ ) )
			int alt7=2;
			try { DebugEnterDecision(7, false);
			int LA7_0 = input.LA(1);

			if ((LA7_0==IDENT))
			{
				alt7 = 1;
			}
			else if ((LA7_0==Type_Tuple))
			{
				alt7 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 7, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:40:4: a= IDENT ( '<' b= type_name ( ',' b= type_name )* '>' )* ( '*' )*
				{
				DebugLocation(40, 5);
				a=(CommonTree)Match(input,IDENT,Follow._IDENT_in_type_name136); 
				DebugLocation(40, 12);
				 value+=a.Text; 
				DebugLocation(40, 32);
				// SugarWalker.g:40:32: ( '<' b= type_name ( ',' b= type_name )* '>' )*
				try { DebugEnterSubRule(4);
				while (true)
				{
					int alt4=2;
					try { DebugEnterDecision(4, false);
					int LA4_0 = input.LA(1);

					if ((LA4_0==46))
					{
						alt4 = 1;
					}


					} finally { DebugExitDecision(4); }
					switch ( alt4 )
					{
					case 1:
						DebugEnterAlt(1);
						// SugarWalker.g:40:33: '<' b= type_name ( ',' b= type_name )* '>'
						{
						DebugLocation(40, 33);
						Match(input,46,Follow._46_in_type_name141); 
						DebugLocation(40, 37);
						 value+="<"; 
						DebugLocation(40, 55);
						PushFollow(Follow._type_name_in_type_name147);
						b=type_name();
						PopFollow();

						DebugLocation(40, 66);
						 value+=b; 
						DebugLocation(40, 81);
						// SugarWalker.g:40:81: ( ',' b= type_name )*
						try { DebugEnterSubRule(3);
						while (true)
						{
							int alt3=2;
							try { DebugEnterDecision(3, false);
							int LA3_0 = input.LA(1);

							if ((LA3_0==41))
							{
								alt3 = 1;
							}


							} finally { DebugExitDecision(3); }
							switch ( alt3 )
							{
							case 1:
								DebugEnterAlt(1);
								// SugarWalker.g:40:82: ',' b= type_name
								{
								DebugLocation(40, 82);
								Match(input,41,Follow._41_in_type_name152); 
								DebugLocation(40, 87);
								PushFollow(Follow._type_name_in_type_name156);
								b=type_name();
								PopFollow();

								DebugLocation(40, 98);
								 value+=", " + b; 

								}
								break;

							default:
								goto loop3;
							}
						}

						loop3:
							;

						} finally { DebugExitSubRule(3); }

						DebugLocation(40, 122);
						Match(input,48,Follow._48_in_type_name162); 
						DebugLocation(40, 126);
						 value+=">"; 

						}
						break;

					default:
						goto loop4;
					}
				}

				loop4:
					;

				} finally { DebugExitSubRule(4); }

				DebugLocation(40, 145);
				// SugarWalker.g:40:145: ( '*' )*
				try { DebugEnterSubRule(5);
				while (true)
				{
					int alt5=2;
					try { DebugEnterDecision(5, false);
					int LA5_0 = input.LA(1);

					if ((LA5_0==38))
					{
						alt5 = 1;
					}


					} finally { DebugExitDecision(5); }
					switch ( alt5 )
					{
					case 1:
						DebugEnterAlt(1);
						// SugarWalker.g:40:146: '*'
						{
						DebugLocation(40, 146);
						Match(input,38,Follow._38_in_type_name169); 
						DebugLocation(40, 150);
						 value+="*"; 

						}
						break;

					default:
						goto loop5;
					}
				}

				loop5:
					;

				} finally { DebugExitSubRule(5); }


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// SugarWalker.g:41:4: ^( Type_Tuple (b= type_name )+ )
				{
				DebugLocation(41, 4);
				bool isFirst = true; value += "std::tuple<";
				DebugLocation(41, 52);
				DebugLocation(41, 54);
				Match(input,Type_Tuple,Follow._Type_Tuple_in_type_name181); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(41, 65);
				// SugarWalker.g:41:65: (b= type_name )+
				int cnt6=0;
				try { DebugEnterSubRule(6);
				while (true)
				{
					int alt6=2;
					try { DebugEnterDecision(6, false);
					int LA6_0 = input.LA(1);

					if ((LA6_0==IDENT||LA6_0==Type_Tuple))
					{
						alt6 = 1;
					}


					} finally { DebugExitDecision(6); }
					switch (alt6)
					{
					case 1:
						DebugEnterAlt(1);
						// SugarWalker.g:41:66: b= type_name
						{
						DebugLocation(41, 67);
						PushFollow(Follow._type_name_in_type_name186);
						b=type_name();
						PopFollow();

						DebugLocation(42, 2);

								if (!isFirst) value += ",";
								isFirst = false;
								value += b;
							

						}
						break;

					default:
						if (cnt6 >= 1)
							goto loop6;

						EarlyExitException eee6 = new EarlyExitException( 6, input );
						DebugRecognitionException(eee6);
						throw eee6;
					}
					cnt6++;
				}
				loop6:
					;

				} finally { DebugExitSubRule(6); }


				Match(input, TokenTypes.Up, null); 

				DebugLocation(47, 2);

						value += ">";
					

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("type_name", 3);
			LeaveRule("type_name", 3);
			LeaveRule_type_name();
		}
		DebugLocation(50, 1);
		} finally { DebugExitRule(GrammarFileName, "type_name"); }
		return value;

	}
	// $ANTLR end "type_name"

	partial void EnterRule_func_def();
	partial void LeaveRule_func_def();

	// $ANTLR start "func_def"
	// SugarWalker.g:52:1: func_def returns [FuncDef value] : a= type_name b= IDENT ( '<' (x= IDENT )+ '>' )? '(' (c= expr ( ',' d= expr IDENT )* )? ')' (e= stmt_block ) ;
	[GrammarRule("func_def")]
	private FuncDef func_def()
	{
		EnterRule_func_def();
		EnterRule("func_def", 4);
		TraceIn("func_def", 4);
		FuncDef value = default(FuncDef);


		CommonTree b = default(CommonTree);
		CommonTree x = default(CommonTree);
		string a = default(string);
		Expr c = default(Expr);
		Expr d = default(Expr);
		StmtBlock e = default(StmtBlock);


			value = new FuncDef();

		try { DebugEnterRule(GrammarFileName, "func_def");
		DebugLocation(52, 1);
		try
		{
			// SugarWalker.g:57:2: (a= type_name b= IDENT ( '<' (x= IDENT )+ '>' )? '(' (c= expr ( ',' d= expr IDENT )* )? ')' (e= stmt_block ) )
			DebugEnterAlt(1);
			// SugarWalker.g:57:4: a= type_name b= IDENT ( '<' (x= IDENT )+ '>' )? '(' (c= expr ( ',' d= expr IDENT )* )? ')' (e= stmt_block )
			{
			DebugLocation(57, 5);
			PushFollow(Follow._type_name_in_func_def217);
			a=type_name();
			PopFollow();

			DebugLocation(57, 17);
			b=(CommonTree)Match(input,IDENT,Follow._IDENT_in_func_def221); 
			DebugLocation(57, 24);
			// SugarWalker.g:57:24: ( '<' (x= IDENT )+ '>' )?
			int alt9=2;
			try { DebugEnterSubRule(9);
			try { DebugEnterDecision(9, false);
			int LA9_0 = input.LA(1);

			if ((LA9_0==46))
			{
				alt9 = 1;
			}
			} finally { DebugExitDecision(9); }
			switch (alt9)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:57:25: '<' (x= IDENT )+ '>'
				{
				DebugLocation(57, 25);
				Match(input,46,Follow._46_in_func_def224); 
				DebugLocation(57, 29);
				// SugarWalker.g:57:29: (x= IDENT )+
				int cnt8=0;
				try { DebugEnterSubRule(8);
				while (true)
				{
					int alt8=2;
					try { DebugEnterDecision(8, false);
					int LA8_0 = input.LA(1);

					if ((LA8_0==IDENT))
					{
						alt8 = 1;
					}


					} finally { DebugExitDecision(8); }
					switch (alt8)
					{
					case 1:
						DebugEnterAlt(1);
						// SugarWalker.g:57:30: x= IDENT
						{
						DebugLocation(57, 31);
						x=(CommonTree)Match(input,IDENT,Follow._IDENT_in_func_def229); 
						DebugLocation(57, 38);
						value.GenericParameter.Add(x.Text); 

						}
						break;

					default:
						if (cnt8 >= 1)
							goto loop8;

						EarlyExitException eee8 = new EarlyExitException( 8, input );
						DebugRecognitionException(eee8);
						throw eee8;
					}
					cnt8++;
				}
				loop8:
					;

				} finally { DebugExitSubRule(8); }

				DebugLocation(57, 80);
				Match(input,48,Follow._48_in_func_def235); 

				}
				break;

			}
			} finally { DebugExitSubRule(9); }

			DebugLocation(57, 86);
			Match(input,36,Follow._36_in_func_def239); 
			DebugLocation(57, 90);
			// SugarWalker.g:57:90: (c= expr ( ',' d= expr IDENT )* )?
			int alt11=2;
			try { DebugEnterSubRule(11);
			try { DebugEnterDecision(11, false);
			int LA11_0 = input.LA(1);

			if ((LA11_0==Expr_Bin||LA11_0==Expr_Call||(LA11_0>=Expr_Dict && LA11_0<=Expr_Dot)||LA11_0==Expr_Prefix||(LA11_0>=Expr_Suffix && LA11_0<=Expr_Tuple)||LA11_0==IDENT||LA11_0==INT||LA11_0==STRING||LA11_0==DOUBLE))
			{
				alt11 = 1;
			}
			} finally { DebugExitDecision(11); }
			switch (alt11)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:57:91: c= expr ( ',' d= expr IDENT )*
				{
				DebugLocation(57, 92);
				PushFollow(Follow._expr_in_func_def244);
				c=expr();
				PopFollow();

				DebugLocation(57, 98);
				 value.Args.Add(c); 
				DebugLocation(57, 122);
				// SugarWalker.g:57:122: ( ',' d= expr IDENT )*
				try { DebugEnterSubRule(10);
				while (true)
				{
					int alt10=2;
					try { DebugEnterDecision(10, false);
					int LA10_0 = input.LA(1);

					if ((LA10_0==41))
					{
						alt10 = 1;
					}


					} finally { DebugExitDecision(10); }
					switch ( alt10 )
					{
					case 1:
						DebugEnterAlt(1);
						// SugarWalker.g:57:123: ',' d= expr IDENT
						{
						DebugLocation(57, 123);
						Match(input,41,Follow._41_in_func_def249); 
						DebugLocation(57, 128);
						PushFollow(Follow._expr_in_func_def253);
						d=expr();
						PopFollow();

						DebugLocation(57, 134);
						 value.Args.Add(d); 
						DebugLocation(57, 158);
						Match(input,IDENT,Follow._IDENT_in_func_def257); 

						}
						break;

					default:
						goto loop10;
					}
				}

				loop10:
					;

				} finally { DebugExitSubRule(10); }


				}
				break;

			}
			} finally { DebugExitSubRule(11); }

			DebugLocation(57, 168);
			Match(input,37,Follow._37_in_func_def263); 
			DebugLocation(58, 2);
			// SugarWalker.g:58:2: (e= stmt_block )
			DebugEnterAlt(1);
			// SugarWalker.g:58:4: e= stmt_block
			{
			DebugLocation(58, 5);
			PushFollow(Follow._stmt_block_in_func_def270);
			e=stmt_block();
			PopFollow();

			DebugLocation(59, 2);

					value.Type = a;
					value.Name = b.Text;
					value.Body = e;
				

			}


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("func_def", 4);
			LeaveRule("func_def", 4);
			LeaveRule_func_def();
		}
		DebugLocation(64, 1);
		} finally { DebugExitRule(GrammarFileName, "func_def"); }
		return value;

	}
	// $ANTLR end "func_def"

	partial void EnterRule_stmt_block();
	partial void LeaveRule_stmt_block();

	// $ANTLR start "stmt_block"
	// SugarWalker.g:66:1: stmt_block returns [StmtBlock value] : INDENT ( ( NEWLINE )+ a= stmt )* ( NEWLINE )* DEDENT ;
	[GrammarRule("stmt_block")]
	private StmtBlock stmt_block()
	{
		EnterRule_stmt_block();
		EnterRule("stmt_block", 5);
		TraceIn("stmt_block", 5);
		StmtBlock value = default(StmtBlock);


		Stmt a = default(Stmt);


			value = new StmtBlock();

		try { DebugEnterRule(GrammarFileName, "stmt_block");
		DebugLocation(66, 4);
		try
		{
			// SugarWalker.g:71:2: ( INDENT ( ( NEWLINE )+ a= stmt )* ( NEWLINE )* DEDENT )
			DebugEnterAlt(1);
			// SugarWalker.g:71:4: INDENT ( ( NEWLINE )+ a= stmt )* ( NEWLINE )* DEDENT
			{
			DebugLocation(71, 4);
			Match(input,INDENT,Follow._INDENT_in_stmt_block294); 
			DebugLocation(71, 11);
			// SugarWalker.g:71:11: ( ( NEWLINE )+ a= stmt )*
			try { DebugEnterSubRule(13);
			while (true)
			{
				int alt13=2;
				try { DebugEnterDecision(13, false);
				try
				{
					alt13 = dfa13.Predict(input);
				}
				catch (NoViableAltException nvae)
				{
					DebugRecognitionException(nvae);
					throw;
				}
				} finally { DebugExitDecision(13); }
				switch ( alt13 )
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:71:12: ( NEWLINE )+ a= stmt
					{
					DebugLocation(71, 12);
					// SugarWalker.g:71:12: ( NEWLINE )+
					int cnt12=0;
					try { DebugEnterSubRule(12);
					while (true)
					{
						int alt12=2;
						try { DebugEnterDecision(12, false);
						int LA12_0 = input.LA(1);

						if ((LA12_0==NEWLINE))
						{
							alt12 = 1;
						}


						} finally { DebugExitDecision(12); }
						switch (alt12)
						{
						case 1:
							DebugEnterAlt(1);
							// SugarWalker.g:71:12: NEWLINE
							{
							DebugLocation(71, 12);
							Match(input,NEWLINE,Follow._NEWLINE_in_stmt_block297); 

							}
							break;

						default:
							if (cnt12 >= 1)
								goto loop12;

							EarlyExitException eee12 = new EarlyExitException( 12, input );
							DebugRecognitionException(eee12);
							throw eee12;
						}
						cnt12++;
					}
					loop12:
						;

					} finally { DebugExitSubRule(12); }

					DebugLocation(71, 22);
					PushFollow(Follow._stmt_in_stmt_block302);
					a=stmt();
					PopFollow();

					DebugLocation(71, 28);
					 value.StmtList.Add(a); 

					}
					break;

				default:
					goto loop13;
				}
			}

			loop13:
				;

			} finally { DebugExitSubRule(13); }

			DebugLocation(71, 58);
			// SugarWalker.g:71:58: ( NEWLINE )*
			try { DebugEnterSubRule(14);
			while (true)
			{
				int alt14=2;
				try { DebugEnterDecision(14, false);
				int LA14_0 = input.LA(1);

				if ((LA14_0==NEWLINE))
				{
					alt14 = 1;
				}


				} finally { DebugExitDecision(14); }
				switch ( alt14 )
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:71:58: NEWLINE
					{
					DebugLocation(71, 58);
					Match(input,NEWLINE,Follow._NEWLINE_in_stmt_block308); 

					}
					break;

				default:
					goto loop14;
				}
			}

			loop14:
				;

			} finally { DebugExitSubRule(14); }

			DebugLocation(71, 67);
			Match(input,DEDENT,Follow._DEDENT_in_stmt_block311); 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("stmt_block", 5);
			LeaveRule("stmt_block", 5);
			LeaveRule_stmt_block();
		}
		DebugLocation(72, 4);
		} finally { DebugExitRule(GrammarFileName, "stmt_block"); }
		return value;

	}
	// $ANTLR end "stmt_block"

	partial void EnterRule_stmt();
	partial void LeaveRule_stmt();

	// $ANTLR start "stmt"
	// SugarWalker.g:74:1: stmt returns [Stmt value] : a= stmt_expr ;
	[GrammarRule("stmt")]
	private Stmt stmt()
	{
		EnterRule_stmt();
		EnterRule("stmt", 6);
		TraceIn("stmt", 6);
		Stmt value = default(Stmt);


		Stmt a = default(Stmt);

		try { DebugEnterRule(GrammarFileName, "stmt");
		DebugLocation(74, 1);
		try
		{
			// SugarWalker.g:75:2: (a= stmt_expr )
			DebugEnterAlt(1);
			// SugarWalker.g:75:4: a= stmt_expr
			{
			DebugLocation(75, 5);
			PushFollow(Follow._stmt_expr_in_stmt332);
			a=stmt_expr();
			PopFollow();

			DebugLocation(75, 16);
			 value = a; 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("stmt", 6);
			LeaveRule("stmt", 6);
			LeaveRule_stmt();
		}
		DebugLocation(76, 1);
		} finally { DebugExitRule(GrammarFileName, "stmt"); }
		return value;

	}
	// $ANTLR end "stmt"

	partial void EnterRule_stmt_expr();
	partial void LeaveRule_stmt_expr();

	// $ANTLR start "stmt_expr"
	// SugarWalker.g:78:1: stmt_expr returns [Stmt value] : (a= stmt_alloc |a= stmt_return );
	[GrammarRule("stmt_expr")]
	private Stmt stmt_expr()
	{
		EnterRule_stmt_expr();
		EnterRule("stmt_expr", 7);
		TraceIn("stmt_expr", 7);
		Stmt value = default(Stmt);


		Stmt a = default(Stmt);

		try { DebugEnterRule(GrammarFileName, "stmt_expr");
		DebugLocation(78, 1);
		try
		{
			// SugarWalker.g:79:2: (a= stmt_alloc |a= stmt_return )
			int alt15=2;
			try { DebugEnterDecision(15, false);
			int LA15_0 = input.LA(1);

			if (((LA15_0>=Expr_Alloc && LA15_0<=Expr_Alloc_Auto)))
			{
				alt15 = 1;
			}
			else if ((LA15_0==Expr_Return))
			{
				alt15 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 15, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(15); }
			switch (alt15)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:79:4: a= stmt_alloc
				{
				DebugLocation(79, 5);
				PushFollow(Follow._stmt_alloc_in_stmt_expr351);
				a=stmt_alloc();
				PopFollow();

				DebugLocation(79, 17);
				 value = a; 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// SugarWalker.g:80:4: a= stmt_return
				{
				DebugLocation(80, 5);
				PushFollow(Follow._stmt_return_in_stmt_expr360);
				a=stmt_return();
				PopFollow();

				DebugLocation(80, 18);
				 value = a; 

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("stmt_expr", 7);
			LeaveRule("stmt_expr", 7);
			LeaveRule_stmt_expr();
		}
		DebugLocation(81, 1);
		} finally { DebugExitRule(GrammarFileName, "stmt_expr"); }
		return value;

	}
	// $ANTLR end "stmt_expr"

	partial void EnterRule_stmt_alloc();
	partial void LeaveRule_stmt_alloc();

	// $ANTLR start "stmt_alloc"
	// SugarWalker.g:83:1: stmt_alloc returns [Stmt value] : (a= alloc_expr |a= alloc_expr_auto );
	[GrammarRule("stmt_alloc")]
	private Stmt stmt_alloc()
	{
		EnterRule_stmt_alloc();
		EnterRule("stmt_alloc", 8);
		TraceIn("stmt_alloc", 8);
		Stmt value = default(Stmt);


		ExprAlloc a = default(ExprAlloc);

		try { DebugEnterRule(GrammarFileName, "stmt_alloc");
		DebugLocation(83, 1);
		try
		{
			// SugarWalker.g:84:2: (a= alloc_expr |a= alloc_expr_auto )
			int alt16=2;
			try { DebugEnterDecision(16, false);
			int LA16_0 = input.LA(1);

			if ((LA16_0==Expr_Alloc))
			{
				alt16 = 1;
			}
			else if ((LA16_0==Expr_Alloc_Auto))
			{
				alt16 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 16, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(16); }
			switch (alt16)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:84:4: a= alloc_expr
				{
				DebugLocation(84, 5);
				PushFollow(Follow._alloc_expr_in_stmt_alloc379);
				a=alloc_expr();
				PopFollow();

				DebugLocation(84, 17);
				 value = a; 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// SugarWalker.g:85:4: a= alloc_expr_auto
				{
				DebugLocation(85, 5);
				PushFollow(Follow._alloc_expr_auto_in_stmt_alloc388);
				a=alloc_expr_auto();
				PopFollow();

				DebugLocation(85, 22);
				 value = a; 

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("stmt_alloc", 8);
			LeaveRule("stmt_alloc", 8);
			LeaveRule_stmt_alloc();
		}
		DebugLocation(86, 1);
		} finally { DebugExitRule(GrammarFileName, "stmt_alloc"); }
		return value;

	}
	// $ANTLR end "stmt_alloc"

	partial void EnterRule_stmt_return();
	partial void LeaveRule_stmt_return();

	// $ANTLR start "stmt_return"
	// SugarWalker.g:88:1: stmt_return returns [Stmt value] : ^( Expr_Return (a= expr )? ) ;
	[GrammarRule("stmt_return")]
	private Stmt stmt_return()
	{
		EnterRule_stmt_return();
		EnterRule("stmt_return", 9);
		TraceIn("stmt_return", 9);
		Stmt value = default(Stmt);


		Expr a = default(Expr);

		try { DebugEnterRule(GrammarFileName, "stmt_return");
		DebugLocation(88, 1);
		try
		{
			// SugarWalker.g:89:2: ( ^( Expr_Return (a= expr )? ) )
			DebugEnterAlt(1);
			// SugarWalker.g:89:4: ^( Expr_Return (a= expr )? )
			{
			DebugLocation(89, 4);
			DebugLocation(89, 6);
			Match(input,Expr_Return,Follow._Expr_Return_in_stmt_return406); 

			if (input.LA(1) == TokenTypes.Down)
			{
				Match(input, TokenTypes.Down, null); 
				DebugLocation(89, 18);
				// SugarWalker.g:89:18: (a= expr )?
				int alt17=2;
				try { DebugEnterSubRule(17);
				try { DebugEnterDecision(17, false);
				int LA17_0 = input.LA(1);

				if ((LA17_0==Expr_Bin||LA17_0==Expr_Call||(LA17_0>=Expr_Dict && LA17_0<=Expr_Dot)||LA17_0==Expr_Prefix||(LA17_0>=Expr_Suffix && LA17_0<=Expr_Tuple)||LA17_0==IDENT||LA17_0==INT||LA17_0==STRING||LA17_0==DOUBLE))
				{
					alt17 = 1;
				}
				} finally { DebugExitDecision(17); }
				switch (alt17)
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:89:19: a= expr
					{
					DebugLocation(89, 20);
					PushFollow(Follow._expr_in_stmt_return411);
					a=expr();
					PopFollow();


					}
					break;

				}
				} finally { DebugExitSubRule(17); }


				Match(input, TokenTypes.Up, null); 
			}

			DebugLocation(90, 2);

					value = new ExprReturn(a);
				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("stmt_return", 9);
			LeaveRule("stmt_return", 9);
			LeaveRule_stmt_return();
		}
		DebugLocation(93, 1);
		} finally { DebugExitRule(GrammarFileName, "stmt_return"); }
		return value;

	}
	// $ANTLR end "stmt_return"

	partial void EnterRule_ident();
	partial void LeaveRule_ident();

	// $ANTLR start "ident"
	// SugarWalker.g:95:1: ident returns [string value] : a= IDENT ;
	[GrammarRule("ident")]
	private string ident()
	{
		EnterRule_ident();
		EnterRule("ident", 10);
		TraceIn("ident", 10);
		string value = default(string);


		CommonTree a = default(CommonTree);

		try { DebugEnterRule(GrammarFileName, "ident");
		DebugLocation(95, 1);
		try
		{
			// SugarWalker.g:96:2: (a= IDENT )
			DebugEnterAlt(1);
			// SugarWalker.g:96:4: a= IDENT
			{
			DebugLocation(96, 5);
			a=(CommonTree)Match(input,IDENT,Follow._IDENT_in_ident434); 
			DebugLocation(96, 12);
			 value = a.Text; 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("ident", 10);
			LeaveRule("ident", 10);
			LeaveRule_ident();
		}
		DebugLocation(97, 1);
		} finally { DebugExitRule(GrammarFileName, "ident"); }
		return value;

	}
	// $ANTLR end "ident"

	partial void EnterRule_ident_list();
	partial void LeaveRule_ident_list();

	// $ANTLR start "ident_list"
	// SugarWalker.g:99:1: ident_list returns [List<string> value] : a= ident ( ( ',' a= ident )+ ';' )? ;
	[GrammarRule("ident_list")]
	private List<string> ident_list()
	{
		EnterRule_ident_list();
		EnterRule("ident_list", 11);
		TraceIn("ident_list", 11);
		List<string> value = default(List<string>);


		string a = default(string);


			value = new List<string>();

		try { DebugEnterRule(GrammarFileName, "ident_list");
		DebugLocation(99, 1);
		try
		{
			// SugarWalker.g:104:2: (a= ident ( ( ',' a= ident )+ ';' )? )
			DebugEnterAlt(1);
			// SugarWalker.g:104:4: a= ident ( ( ',' a= ident )+ ';' )?
			{
			DebugLocation(104, 5);
			PushFollow(Follow._ident_in_ident_list458);
			a=ident();
			PopFollow();

			DebugLocation(104, 12);
			 value.Add(a); 
			DebugLocation(104, 31);
			// SugarWalker.g:104:31: ( ( ',' a= ident )+ ';' )?
			int alt19=2;
			try { DebugEnterSubRule(19);
			try { DebugEnterDecision(19, false);
			int LA19_0 = input.LA(1);

			if ((LA19_0==41))
			{
				alt19 = 1;
			}
			} finally { DebugExitDecision(19); }
			switch (alt19)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:104:32: ( ',' a= ident )+ ';'
				{
				DebugLocation(104, 32);
				// SugarWalker.g:104:32: ( ',' a= ident )+
				int cnt18=0;
				try { DebugEnterSubRule(18);
				while (true)
				{
					int alt18=2;
					try { DebugEnterDecision(18, false);
					int LA18_0 = input.LA(1);

					if ((LA18_0==41))
					{
						alt18 = 1;
					}


					} finally { DebugExitDecision(18); }
					switch (alt18)
					{
					case 1:
						DebugEnterAlt(1);
						// SugarWalker.g:104:33: ',' a= ident
						{
						DebugLocation(104, 33);
						Match(input,41,Follow._41_in_ident_list464); 
						DebugLocation(104, 38);
						PushFollow(Follow._ident_in_ident_list468);
						a=ident();
						PopFollow();

						DebugLocation(104, 45);
						 value.Add(a); 

						}
						break;

					default:
						if (cnt18 >= 1)
							goto loop18;

						EarlyExitException eee18 = new EarlyExitException( 18, input );
						DebugRecognitionException(eee18);
						throw eee18;
					}
					cnt18++;
				}
				loop18:
					;

				} finally { DebugExitSubRule(18); }

				DebugLocation(104, 66);
				Match(input,55,Follow._55_in_ident_list474); 

				}
				break;

			}
			} finally { DebugExitSubRule(19); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("ident_list", 11);
			LeaveRule("ident_list", 11);
			LeaveRule_ident_list();
		}
		DebugLocation(105, 1);
		} finally { DebugExitRule(GrammarFileName, "ident_list"); }
		return value;

	}
	// $ANTLR end "ident_list"

	partial void EnterRule_alloc_expr();
	partial void LeaveRule_alloc_expr();

	// $ANTLR start "alloc_expr"
	// SugarWalker.g:107:1: alloc_expr returns [ExprAlloc value] : ^( Expr_Alloc a= type_name b= ident (c= expr )? ) ;
	[GrammarRule("alloc_expr")]
	private ExprAlloc alloc_expr()
	{
		EnterRule_alloc_expr();
		EnterRule("alloc_expr", 12);
		TraceIn("alloc_expr", 12);
		ExprAlloc value = default(ExprAlloc);


		string a = default(string);
		string b = default(string);
		Expr c = default(Expr);

		try { DebugEnterRule(GrammarFileName, "alloc_expr");
		DebugLocation(107, 1);
		try
		{
			// SugarWalker.g:108:2: ( ^( Expr_Alloc a= type_name b= ident (c= expr )? ) )
			DebugEnterAlt(1);
			// SugarWalker.g:108:4: ^( Expr_Alloc a= type_name b= ident (c= expr )? )
			{
			DebugLocation(108, 4);
			DebugLocation(108, 6);
			Match(input,Expr_Alloc,Follow._Expr_Alloc_in_alloc_expr493); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(108, 18);
			PushFollow(Follow._type_name_in_alloc_expr497);
			a=type_name();
			PopFollow();

			DebugLocation(108, 30);
			PushFollow(Follow._ident_in_alloc_expr501);
			b=ident();
			PopFollow();

			DebugLocation(108, 37);
			// SugarWalker.g:108:37: (c= expr )?
			int alt20=2;
			try { DebugEnterSubRule(20);
			try { DebugEnterDecision(20, false);
			int LA20_0 = input.LA(1);

			if ((LA20_0==Expr_Bin||LA20_0==Expr_Call||(LA20_0>=Expr_Dict && LA20_0<=Expr_Dot)||LA20_0==Expr_Prefix||(LA20_0>=Expr_Suffix && LA20_0<=Expr_Tuple)||LA20_0==IDENT||LA20_0==INT||LA20_0==STRING||LA20_0==DOUBLE))
			{
				alt20 = 1;
			}
			} finally { DebugExitDecision(20); }
			switch (alt20)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:108:38: c= expr
				{
				DebugLocation(108, 39);
				PushFollow(Follow._expr_in_alloc_expr506);
				c=expr();
				PopFollow();


				}
				break;

			}
			} finally { DebugExitSubRule(20); }


			Match(input, TokenTypes.Up, null); 

			DebugLocation(109, 2);

					value = new ExprAlloc();
					value.Type = a;
					value.Name = b;
					value.Expr = c;
				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("alloc_expr", 12);
			LeaveRule("alloc_expr", 12);
			LeaveRule_alloc_expr();
		}
		DebugLocation(115, 1);
		} finally { DebugExitRule(GrammarFileName, "alloc_expr"); }
		return value;

	}
	// $ANTLR end "alloc_expr"

	partial void EnterRule_alloc_expr_auto();
	partial void LeaveRule_alloc_expr_auto();

	// $ANTLR start "alloc_expr_auto"
	// SugarWalker.g:117:1: alloc_expr_auto returns [ExprAlloc value] : ^( Expr_Alloc_Auto a= ident (b= expr )? ) ;
	[GrammarRule("alloc_expr_auto")]
	private ExprAlloc alloc_expr_auto()
	{
		EnterRule_alloc_expr_auto();
		EnterRule("alloc_expr_auto", 13);
		TraceIn("alloc_expr_auto", 13);
		ExprAlloc value = default(ExprAlloc);


		string a = default(string);
		Expr b = default(Expr);

		try { DebugEnterRule(GrammarFileName, "alloc_expr_auto");
		DebugLocation(117, 1);
		try
		{
			// SugarWalker.g:118:2: ( ^( Expr_Alloc_Auto a= ident (b= expr )? ) )
			DebugEnterAlt(1);
			// SugarWalker.g:118:4: ^( Expr_Alloc_Auto a= ident (b= expr )? )
			{
			DebugLocation(118, 4);
			DebugLocation(118, 6);
			Match(input,Expr_Alloc_Auto,Follow._Expr_Alloc_Auto_in_alloc_expr_auto528); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(118, 23);
			PushFollow(Follow._ident_in_alloc_expr_auto532);
			a=ident();
			PopFollow();

			DebugLocation(118, 30);
			// SugarWalker.g:118:30: (b= expr )?
			int alt21=2;
			try { DebugEnterSubRule(21);
			try { DebugEnterDecision(21, false);
			int LA21_0 = input.LA(1);

			if ((LA21_0==Expr_Bin||LA21_0==Expr_Call||(LA21_0>=Expr_Dict && LA21_0<=Expr_Dot)||LA21_0==Expr_Prefix||(LA21_0>=Expr_Suffix && LA21_0<=Expr_Tuple)||LA21_0==IDENT||LA21_0==INT||LA21_0==STRING||LA21_0==DOUBLE))
			{
				alt21 = 1;
			}
			} finally { DebugExitDecision(21); }
			switch (alt21)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:118:31: b= expr
				{
				DebugLocation(118, 32);
				PushFollow(Follow._expr_in_alloc_expr_auto537);
				b=expr();
				PopFollow();


				}
				break;

			}
			} finally { DebugExitSubRule(21); }


			Match(input, TokenTypes.Up, null); 

			DebugLocation(119, 2);

					value = new ExprAlloc();
					value.Type = "auto";
					value.Name = a;
					value.Expr = b;
				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("alloc_expr_auto", 13);
			LeaveRule("alloc_expr_auto", 13);
			LeaveRule_alloc_expr_auto();
		}
		DebugLocation(125, 1);
		} finally { DebugExitRule(GrammarFileName, "alloc_expr_auto"); }
		return value;

	}
	// $ANTLR end "alloc_expr_auto"

	partial void EnterRule_new_expr();
	partial void LeaveRule_new_expr();

	// $ANTLR start "new_expr"
	// SugarWalker.g:127:1: new_expr returns [ExprNew value] : ^( Expr_New a= IDENT (b= expr )+ ) ;
	[GrammarRule("new_expr")]
	private ExprNew new_expr()
	{
		EnterRule_new_expr();
		EnterRule("new_expr", 14);
		TraceIn("new_expr", 14);
		ExprNew value = default(ExprNew);


		CommonTree a = default(CommonTree);
		Expr b = default(Expr);


			value = new ExprNew();

		try { DebugEnterRule(GrammarFileName, "new_expr");
		DebugLocation(127, 1);
		try
		{
			// SugarWalker.g:132:2: ( ^( Expr_New a= IDENT (b= expr )+ ) )
			DebugEnterAlt(1);
			// SugarWalker.g:132:4: ^( Expr_New a= IDENT (b= expr )+ )
			{
			DebugLocation(132, 4);
			DebugLocation(132, 6);
			Match(input,Expr_New,Follow._Expr_New_in_new_expr564); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(132, 16);
			a=(CommonTree)Match(input,IDENT,Follow._IDENT_in_new_expr568); 
			DebugLocation(132, 23);
			 value.ElemType = a.Text; 
			DebugLocation(132, 53);
			// SugarWalker.g:132:53: (b= expr )+
			int cnt22=0;
			try { DebugEnterSubRule(22);
			while (true)
			{
				int alt22=2;
				try { DebugEnterDecision(22, false);
				int LA22_0 = input.LA(1);

				if ((LA22_0==Expr_Bin||LA22_0==Expr_Call||(LA22_0>=Expr_Dict && LA22_0<=Expr_Dot)||LA22_0==Expr_Prefix||(LA22_0>=Expr_Suffix && LA22_0<=Expr_Tuple)||LA22_0==IDENT||LA22_0==INT||LA22_0==STRING||LA22_0==DOUBLE))
				{
					alt22 = 1;
				}


				} finally { DebugExitDecision(22); }
				switch (alt22)
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:132:54: b= expr
					{
					DebugLocation(132, 55);
					PushFollow(Follow._expr_in_new_expr575);
					b=expr();
					PopFollow();

					DebugLocation(132, 61);
					 value.Ranges.Add(b); 

					}
					break;

				default:
					if (cnt22 >= 1)
						goto loop22;

					EarlyExitException eee22 = new EarlyExitException( 22, input );
					DebugRecognitionException(eee22);
					throw eee22;
				}
				cnt22++;
			}
			loop22:
				;

			} finally { DebugExitSubRule(22); }


			Match(input, TokenTypes.Up, null); 


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("new_expr", 14);
			LeaveRule("new_expr", 14);
			LeaveRule_new_expr();
		}
		DebugLocation(133, 1);
		} finally { DebugExitRule(GrammarFileName, "new_expr"); }
		return value;

	}
	// $ANTLR end "new_expr"

	partial void EnterRule_block_expr();
	partial void LeaveRule_block_expr();

	// $ANTLR start "block_expr"
	// SugarWalker.g:135:1: block_expr returns [ExprBlock value] : INDENT ( ( NEWLINE )+ a= stmt )* ( NEWLINE )* DEDENT ;
	[GrammarRule("block_expr")]
	private ExprBlock block_expr()
	{
		EnterRule_block_expr();
		EnterRule("block_expr", 15);
		TraceIn("block_expr", 15);
		ExprBlock value = default(ExprBlock);


		Stmt a = default(Stmt);


			value = new ExprBlock();

		try { DebugEnterRule(GrammarFileName, "block_expr");
		DebugLocation(135, 4);
		try
		{
			// SugarWalker.g:140:2: ( INDENT ( ( NEWLINE )+ a= stmt )* ( NEWLINE )* DEDENT )
			DebugEnterAlt(1);
			// SugarWalker.g:140:4: INDENT ( ( NEWLINE )+ a= stmt )* ( NEWLINE )* DEDENT
			{
			DebugLocation(140, 4);
			Match(input,INDENT,Follow._INDENT_in_block_expr600); 
			DebugLocation(140, 11);
			// SugarWalker.g:140:11: ( ( NEWLINE )+ a= stmt )*
			try { DebugEnterSubRule(24);
			while (true)
			{
				int alt24=2;
				try { DebugEnterDecision(24, false);
				try
				{
					alt24 = dfa24.Predict(input);
				}
				catch (NoViableAltException nvae)
				{
					DebugRecognitionException(nvae);
					throw;
				}
				} finally { DebugExitDecision(24); }
				switch ( alt24 )
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:140:12: ( NEWLINE )+ a= stmt
					{
					DebugLocation(140, 12);
					// SugarWalker.g:140:12: ( NEWLINE )+
					int cnt23=0;
					try { DebugEnterSubRule(23);
					while (true)
					{
						int alt23=2;
						try { DebugEnterDecision(23, false);
						int LA23_0 = input.LA(1);

						if ((LA23_0==NEWLINE))
						{
							alt23 = 1;
						}


						} finally { DebugExitDecision(23); }
						switch (alt23)
						{
						case 1:
							DebugEnterAlt(1);
							// SugarWalker.g:140:12: NEWLINE
							{
							DebugLocation(140, 12);
							Match(input,NEWLINE,Follow._NEWLINE_in_block_expr603); 

							}
							break;

						default:
							if (cnt23 >= 1)
								goto loop23;

							EarlyExitException eee23 = new EarlyExitException( 23, input );
							DebugRecognitionException(eee23);
							throw eee23;
						}
						cnt23++;
					}
					loop23:
						;

					} finally { DebugExitSubRule(23); }

					DebugLocation(140, 22);
					PushFollow(Follow._stmt_in_block_expr608);
					a=stmt();
					PopFollow();

					DebugLocation(140, 28);
					 value.StmtList.Add(a); 

					}
					break;

				default:
					goto loop24;
				}
			}

			loop24:
				;

			} finally { DebugExitSubRule(24); }

			DebugLocation(140, 58);
			// SugarWalker.g:140:58: ( NEWLINE )*
			try { DebugEnterSubRule(25);
			while (true)
			{
				int alt25=2;
				try { DebugEnterDecision(25, false);
				int LA25_0 = input.LA(1);

				if ((LA25_0==NEWLINE))
				{
					alt25 = 1;
				}


				} finally { DebugExitDecision(25); }
				switch ( alt25 )
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:140:58: NEWLINE
					{
					DebugLocation(140, 58);
					Match(input,NEWLINE,Follow._NEWLINE_in_block_expr614); 

					}
					break;

				default:
					goto loop25;
				}
			}

			loop25:
				;

			} finally { DebugExitSubRule(25); }

			DebugLocation(140, 67);
			Match(input,DEDENT,Follow._DEDENT_in_block_expr617); 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("block_expr", 15);
			LeaveRule("block_expr", 15);
			LeaveRule_block_expr();
		}
		DebugLocation(141, 4);
		} finally { DebugExitRule(GrammarFileName, "block_expr"); }
		return value;

	}
	// $ANTLR end "block_expr"

	partial void EnterRule_expr_tuple();
	partial void LeaveRule_expr_tuple();

	// $ANTLR start "expr_tuple"
	// SugarWalker.g:143:1: expr_tuple returns [ExprTuple value] : ^( Expr_Tuple (a= expr )+ ) ;
	[GrammarRule("expr_tuple")]
	private ExprTuple expr_tuple()
	{
		EnterRule_expr_tuple();
		EnterRule("expr_tuple", 16);
		TraceIn("expr_tuple", 16);
		ExprTuple value = default(ExprTuple);


		Expr a = default(Expr);


			value = new ExprTuple();

		try { DebugEnterRule(GrammarFileName, "expr_tuple");
		DebugLocation(143, 1);
		try
		{
			// SugarWalker.g:148:2: ( ^( Expr_Tuple (a= expr )+ ) )
			DebugEnterAlt(1);
			// SugarWalker.g:148:4: ^( Expr_Tuple (a= expr )+ )
			{
			DebugLocation(148, 4);
			DebugLocation(148, 6);
			Match(input,Expr_Tuple,Follow._Expr_Tuple_in_expr_tuple642); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(148, 17);
			// SugarWalker.g:148:17: (a= expr )+
			int cnt26=0;
			try { DebugEnterSubRule(26);
			while (true)
			{
				int alt26=2;
				try { DebugEnterDecision(26, false);
				int LA26_0 = input.LA(1);

				if ((LA26_0==Expr_Bin||LA26_0==Expr_Call||(LA26_0>=Expr_Dict && LA26_0<=Expr_Dot)||LA26_0==Expr_Prefix||(LA26_0>=Expr_Suffix && LA26_0<=Expr_Tuple)||LA26_0==IDENT||LA26_0==INT||LA26_0==STRING||LA26_0==DOUBLE))
				{
					alt26 = 1;
				}


				} finally { DebugExitDecision(26); }
				switch (alt26)
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:148:18: a= expr
					{
					DebugLocation(148, 19);
					PushFollow(Follow._expr_in_expr_tuple647);
					a=expr();
					PopFollow();

					DebugLocation(148, 25);
					 value.ExprList.Add(a); 

					}
					break;

				default:
					if (cnt26 >= 1)
						goto loop26;

					EarlyExitException eee26 = new EarlyExitException( 26, input );
					DebugRecognitionException(eee26);
					throw eee26;
				}
				cnt26++;
			}
			loop26:
				;

			} finally { DebugExitSubRule(26); }


			Match(input, TokenTypes.Up, null); 


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("expr_tuple", 16);
			LeaveRule("expr_tuple", 16);
			LeaveRule_expr_tuple();
		}
		DebugLocation(149, 1);
		} finally { DebugExitRule(GrammarFileName, "expr_tuple"); }
		return value;

	}
	// $ANTLR end "expr_tuple"

	partial void EnterRule_expr_match_tuple();
	partial void LeaveRule_expr_match_tuple();

	// $ANTLR start "expr_match_tuple"
	// SugarWalker.g:151:1: expr_match_tuple returns [MatchTuple value] : ^( Expr_Match_Tuple (a= IDENT )* ) ;
	[GrammarRule("expr_match_tuple")]
	private MatchTuple expr_match_tuple()
	{
		EnterRule_expr_match_tuple();
		EnterRule("expr_match_tuple", 17);
		TraceIn("expr_match_tuple", 17);
		MatchTuple value = default(MatchTuple);


		CommonTree a = default(CommonTree);


			value = new MatchTuple();

		try { DebugEnterRule(GrammarFileName, "expr_match_tuple");
		DebugLocation(151, 1);
		try
		{
			// SugarWalker.g:156:2: ( ^( Expr_Match_Tuple (a= IDENT )* ) )
			DebugEnterAlt(1);
			// SugarWalker.g:156:4: ^( Expr_Match_Tuple (a= IDENT )* )
			{
			DebugLocation(156, 4);
			DebugLocation(156, 6);
			Match(input,Expr_Match_Tuple,Follow._Expr_Match_Tuple_in_expr_match_tuple674); 

			if (input.LA(1) == TokenTypes.Down)
			{
				Match(input, TokenTypes.Down, null); 
				DebugLocation(156, 23);
				// SugarWalker.g:156:23: (a= IDENT )*
				try { DebugEnterSubRule(27);
				while (true)
				{
					int alt27=2;
					try { DebugEnterDecision(27, false);
					int LA27_0 = input.LA(1);

					if ((LA27_0==IDENT))
					{
						alt27 = 1;
					}


					} finally { DebugExitDecision(27); }
					switch ( alt27 )
					{
					case 1:
						DebugEnterAlt(1);
						// SugarWalker.g:156:24: a= IDENT
						{
						DebugLocation(156, 25);
						a=(CommonTree)Match(input,IDENT,Follow._IDENT_in_expr_match_tuple679); 
						DebugLocation(156, 32);
						 value.VarList.Add(a.Text); 

						}
						break;

					default:
						goto loop27;
					}
				}

				loop27:
					;

				} finally { DebugExitSubRule(27); }


				Match(input, TokenTypes.Up, null); 
			}


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("expr_match_tuple", 17);
			LeaveRule("expr_match_tuple", 17);
			LeaveRule_expr_match_tuple();
		}
		DebugLocation(157, 1);
		} finally { DebugExitRule(GrammarFileName, "expr_match_tuple"); }
		return value;

	}
	// $ANTLR end "expr_match_tuple"

	partial void EnterRule_expr_list();
	partial void LeaveRule_expr_list();

	// $ANTLR start "expr_list"
	// SugarWalker.g:159:1: expr_list returns [List<Expr> value] : (a= expr )* ;
	[GrammarRule("expr_list")]
	private List<Expr> expr_list()
	{
		EnterRule_expr_list();
		EnterRule("expr_list", 18);
		TraceIn("expr_list", 18);
		List<Expr> value = default(List<Expr>);


		Expr a = default(Expr);


			value = new List<Expr>();

		try { DebugEnterRule(GrammarFileName, "expr_list");
		DebugLocation(159, 1);
		try
		{
			// SugarWalker.g:164:2: ( (a= expr )* )
			DebugEnterAlt(1);
			// SugarWalker.g:164:4: (a= expr )*
			{
			DebugLocation(164, 4);
			// SugarWalker.g:164:4: (a= expr )*
			try { DebugEnterSubRule(28);
			while (true)
			{
				int alt28=2;
				try { DebugEnterDecision(28, false);
				int LA28_0 = input.LA(1);

				if ((LA28_0==Expr_Bin||LA28_0==Expr_Call||(LA28_0>=Expr_Dict && LA28_0<=Expr_Dot)||LA28_0==Expr_Prefix||(LA28_0>=Expr_Suffix && LA28_0<=Expr_Tuple)||LA28_0==IDENT||LA28_0==INT||LA28_0==STRING||LA28_0==DOUBLE))
				{
					alt28 = 1;
				}


				} finally { DebugExitDecision(28); }
				switch ( alt28 )
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:164:5: a= expr
					{
					DebugLocation(164, 6);
					PushFollow(Follow._expr_in_expr_list707);
					a=expr();
					PopFollow();

					DebugLocation(164, 12);
					 value.Add(a); 

					}
					break;

				default:
					goto loop28;
				}
			}

			loop28:
				;

			} finally { DebugExitSubRule(28); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("expr_list", 18);
			LeaveRule("expr_list", 18);
			LeaveRule_expr_list();
		}
		DebugLocation(165, 1);
		} finally { DebugExitRule(GrammarFileName, "expr_list"); }
		return value;

	}
	// $ANTLR end "expr_list"

	partial void EnterRule_call_expr();
	partial void LeaveRule_call_expr();

	// $ANTLR start "call_expr"
	// SugarWalker.g:167:1: call_expr returns [Expr value] : ^( Expr_Call a= expr b= expr_list ) ;
	[GrammarRule("call_expr")]
	private Expr call_expr()
	{
		EnterRule_call_expr();
		EnterRule("call_expr", 19);
		TraceIn("call_expr", 19);
		Expr value = default(Expr);


		Expr a = default(Expr);
		List<Expr> b = default(List<Expr>);

		try { DebugEnterRule(GrammarFileName, "call_expr");
		DebugLocation(167, 1);
		try
		{
			// SugarWalker.g:168:2: ( ^( Expr_Call a= expr b= expr_list ) )
			DebugEnterAlt(1);
			// SugarWalker.g:168:4: ^( Expr_Call a= expr b= expr_list )
			{
			DebugLocation(168, 4);
			DebugLocation(168, 6);
			Match(input,Expr_Call,Follow._Expr_Call_in_call_expr727); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(168, 17);
			PushFollow(Follow._expr_in_call_expr731);
			a=expr();
			PopFollow();

			DebugLocation(168, 24);
			PushFollow(Follow._expr_list_in_call_expr735);
			b=expr_list();
			PopFollow();


			Match(input, TokenTypes.Up, null); 

			DebugLocation(169, 2);

					value = new ExprCall(a, b);
				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("call_expr", 19);
			LeaveRule("call_expr", 19);
			LeaveRule_call_expr();
		}
		DebugLocation(172, 1);
		} finally { DebugExitRule(GrammarFileName, "call_expr"); }
		return value;

	}
	// $ANTLR end "call_expr"

	partial void EnterRule_dict_expr();
	partial void LeaveRule_dict_expr();

	// $ANTLR start "dict_expr"
	// SugarWalker.g:174:1: dict_expr returns [Expr value] : ^( Expr_Dict a= expr b= expr ) ;
	[GrammarRule("dict_expr")]
	private Expr dict_expr()
	{
		EnterRule_dict_expr();
		EnterRule("dict_expr", 20);
		TraceIn("dict_expr", 20);
		Expr value = default(Expr);


		Expr a = default(Expr);
		Expr b = default(Expr);

		try { DebugEnterRule(GrammarFileName, "dict_expr");
		DebugLocation(174, 1);
		try
		{
			// SugarWalker.g:175:2: ( ^( Expr_Dict a= expr b= expr ) )
			DebugEnterAlt(1);
			// SugarWalker.g:175:4: ^( Expr_Dict a= expr b= expr )
			{
			DebugLocation(175, 4);
			DebugLocation(175, 6);
			Match(input,Expr_Dict,Follow._Expr_Dict_in_dict_expr755); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(175, 17);
			PushFollow(Follow._expr_in_dict_expr759);
			a=expr();
			PopFollow();

			DebugLocation(175, 24);
			PushFollow(Follow._expr_in_dict_expr763);
			b=expr();
			PopFollow();


			Match(input, TokenTypes.Up, null); 

			DebugLocation(176, 2);

					value = new ExprDict(a, b);
				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("dict_expr", 20);
			LeaveRule("dict_expr", 20);
			LeaveRule_dict_expr();
		}
		DebugLocation(179, 1);
		} finally { DebugExitRule(GrammarFileName, "dict_expr"); }
		return value;

	}
	// $ANTLR end "dict_expr"

	partial void EnterRule_expr();
	partial void LeaveRule_expr();

	// $ANTLR start "expr"
	// SugarWalker.g:181:1: expr returns [Expr value] : (tuple= expr_tuple |call= call_expr |dict= dict_expr | ^( Expr_Dot a= expr text= IDENT ) | ^( Expr_Bin op= ( '+' | '-' | '*' | '/' ) a= expr b= expr ) | ^( Expr_Suffix op= ( '++' | '--' ) a= expr ) | ^( Expr_Prefix op= ( '++' | '--' | '!' | '~' ) a= expr ) |text= ( INT | DOUBLE | IDENT | STRING ) );
	[GrammarRule("expr")]
	private Expr expr()
	{
		EnterRule_expr();
		EnterRule("expr", 21);
		TraceIn("expr", 21);
		Expr value = default(Expr);


		CommonTree text = default(CommonTree);
		CommonTree op = default(CommonTree);
		ExprTuple tuple = default(ExprTuple);
		Expr call = default(Expr);
		Expr dict = default(Expr);
		Expr a = default(Expr);
		Expr b = default(Expr);

		try { DebugEnterRule(GrammarFileName, "expr");
		DebugLocation(181, 1);
		try
		{
			// SugarWalker.g:182:5: (tuple= expr_tuple |call= call_expr |dict= dict_expr | ^( Expr_Dot a= expr text= IDENT ) | ^( Expr_Bin op= ( '+' | '-' | '*' | '/' ) a= expr b= expr ) | ^( Expr_Suffix op= ( '++' | '--' ) a= expr ) | ^( Expr_Prefix op= ( '++' | '--' | '!' | '~' ) a= expr ) |text= ( INT | DOUBLE | IDENT | STRING ) )
			int alt29=8;
			try { DebugEnterDecision(29, false);
			switch (input.LA(1))
			{
			case Expr_Tuple:
				{
				alt29 = 1;
				}
				break;
			case Expr_Call:
				{
				alt29 = 2;
				}
				break;
			case Expr_Dict:
				{
				alt29 = 3;
				}
				break;
			case Expr_Dot:
				{
				alt29 = 4;
				}
				break;
			case Expr_Bin:
				{
				alt29 = 5;
				}
				break;
			case Expr_Suffix:
				{
				alt29 = 6;
				}
				break;
			case Expr_Prefix:
				{
				alt29 = 7;
				}
				break;
			case IDENT:
			case INT:
			case STRING:
			case DOUBLE:
				{
				alt29 = 8;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 29, 0, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(29); }
			switch (alt29)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:182:7: tuple= expr_tuple
				{
				DebugLocation(182, 12);
				PushFollow(Follow._expr_tuple_in_expr787);
				tuple=expr_tuple();
				PopFollow();

				DebugLocation(183, 2);

						value = tuple;
					

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// SugarWalker.g:186:4: call= call_expr
				{
				DebugLocation(186, 8);
				PushFollow(Follow._call_expr_in_expr797);
				call=call_expr();
				PopFollow();

				DebugLocation(187, 2);

						value = call;
					

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// SugarWalker.g:190:4: dict= dict_expr
				{
				DebugLocation(190, 8);
				PushFollow(Follow._dict_expr_in_expr807);
				dict=dict_expr();
				PopFollow();

				DebugLocation(191, 2);

						value = dict;
					

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// SugarWalker.g:194:4: ^( Expr_Dot a= expr text= IDENT )
				{
				DebugLocation(194, 4);
				DebugLocation(194, 6);
				Match(input,Expr_Dot,Follow._Expr_Dot_in_expr816); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(194, 16);
				PushFollow(Follow._expr_in_expr820);
				a=expr();
				PopFollow();

				DebugLocation(194, 26);
				text=(CommonTree)Match(input,IDENT,Follow._IDENT_in_expr824); 

				Match(input, TokenTypes.Up, null); 

				DebugLocation(195, 2);

						value = new ExprDot(a, text.Text);
					

				}
				break;
			case 5:
				DebugEnterAlt(5);
				// SugarWalker.g:198:4: ^( Expr_Bin op= ( '+' | '-' | '*' | '/' ) a= expr b= expr )
				{
				DebugLocation(198, 4);
				DebugLocation(198, 6);
				Match(input,Expr_Bin,Follow._Expr_Bin_in_expr834); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(198, 17);

				op=(CommonTree)input.LT(1);
				if ((input.LA(1)>=38 && input.LA(1)<=39)||input.LA(1)==42||input.LA(1)==45)
				{
					input.Consume();
					state.errorRecovery=false;
				}
				else
				{
					MismatchedSetException mse = new MismatchedSetException(null,input);
					DebugRecognitionException(mse);
					throw mse;
				}

				DebugLocation(198, 43);
				PushFollow(Follow._expr_in_expr856);
				a=expr();
				PopFollow();

				DebugLocation(198, 50);
				PushFollow(Follow._expr_in_expr860);
				b=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(199, 2);

						value = new ExprBin(op.Text, a, b);
					

				}
				break;
			case 6:
				DebugEnterAlt(6);
				// SugarWalker.g:202:4: ^( Expr_Suffix op= ( '++' | '--' ) a= expr )
				{
				DebugLocation(202, 4);
				DebugLocation(202, 6);
				Match(input,Expr_Suffix,Follow._Expr_Suffix_in_expr870); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(202, 20);

				op=(CommonTree)input.LT(1);
				if (input.LA(1)==40||input.LA(1)==43)
				{
					input.Consume();
					state.errorRecovery=false;
				}
				else
				{
					MismatchedSetException mse = new MismatchedSetException(null,input);
					DebugRecognitionException(mse);
					throw mse;
				}

				DebugLocation(202, 36);
				PushFollow(Follow._expr_in_expr884);
				a=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(203, 2);

						value = new ExprSuffix(op.Text, a);
					

				}
				break;
			case 7:
				DebugEnterAlt(7);
				// SugarWalker.g:206:4: ^( Expr_Prefix op= ( '++' | '--' | '!' | '~' ) a= expr )
				{
				DebugLocation(206, 4);
				DebugLocation(206, 6);
				Match(input,Expr_Prefix,Follow._Expr_Prefix_in_expr894); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(206, 20);

				op=(CommonTree)input.LT(1);
				if (input.LA(1)==34||input.LA(1)==40||input.LA(1)==43||input.LA(1)==53)
				{
					input.Consume();
					state.errorRecovery=false;
				}
				else
				{
					MismatchedSetException mse = new MismatchedSetException(null,input);
					DebugRecognitionException(mse);
					throw mse;
				}

				DebugLocation(206, 48);
				PushFollow(Follow._expr_in_expr916);
				a=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(207, 2);

						value = new ExprPrefix(op.Text, a);
					

				}
				break;
			case 8:
				DebugEnterAlt(8);
				// SugarWalker.g:210:4: text= ( INT | DOUBLE | IDENT | STRING )
				{
				DebugLocation(210, 8);

				text=(CommonTree)input.LT(1);
				if (input.LA(1)==IDENT||input.LA(1)==INT||input.LA(1)==STRING||input.LA(1)==DOUBLE)
				{
					input.Consume();
					state.errorRecovery=false;
				}
				else
				{
					MismatchedSetException mse = new MismatchedSetException(null,input);
					DebugRecognitionException(mse);
					throw mse;
				}

				DebugLocation(211, 5);

				        value = new ExprConst(text.Text);
				    

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("expr", 21);
			LeaveRule("expr", 21);
			LeaveRule_expr();
		}
		DebugLocation(214, 1);
		} finally { DebugExitRule(GrammarFileName, "expr"); }
		return value;

	}
	// $ANTLR end "expr"
	#endregion Rules


	#region DFA
	private DFA13 dfa13;
	private DFA24 dfa24;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa13 = new DFA13( this );
		dfa24 = new DFA24( this );
	}

	private class DFA13 : DFA
	{
		private const string DFA13_eotS =
			"\x4\xFFFF";
		private const string DFA13_eofS =
			"\x4\xFFFF";
		private const string DFA13_minS =
			"\x2\x5\x2\xFFFF";
		private const string DFA13_maxS =
			"\x2\x1A\x2\xFFFF";
		private const string DFA13_acceptS =
			"\x2\xFFFF\x1\x2\x1\x1";
		private const string DFA13_specialS =
			"\x4\xFFFF}>";
		private static readonly string[] DFA13_transitionS =
			{
				"\x1\x2\x14\xFFFF\x1\x1",
				"\x1\x2\x1\xFFFF\x2\x3\x9\xFFFF\x1\x3\x7\xFFFF\x1\x1",
				"",
				""
			};

		private static readonly short[] DFA13_eot = DFA.UnpackEncodedString(DFA13_eotS);
		private static readonly short[] DFA13_eof = DFA.UnpackEncodedString(DFA13_eofS);
		private static readonly char[] DFA13_min = DFA.UnpackEncodedStringToUnsignedChars(DFA13_minS);
		private static readonly char[] DFA13_max = DFA.UnpackEncodedStringToUnsignedChars(DFA13_maxS);
		private static readonly short[] DFA13_accept = DFA.UnpackEncodedString(DFA13_acceptS);
		private static readonly short[] DFA13_special = DFA.UnpackEncodedString(DFA13_specialS);
		private static readonly short[][] DFA13_transition;

		static DFA13()
		{
			int numStates = DFA13_transitionS.Length;
			DFA13_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA13_transition[i] = DFA.UnpackEncodedString(DFA13_transitionS[i]);
			}
		}

		public DFA13( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 13;
			this.eot = DFA13_eot;
			this.eof = DFA13_eof;
			this.min = DFA13_min;
			this.max = DFA13_max;
			this.accept = DFA13_accept;
			this.special = DFA13_special;
			this.transition = DFA13_transition;
		}

		public override string Description { get { return "()* loopback of 71:11: ( ( NEWLINE )+ a= stmt )*"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA24 : DFA
	{
		private const string DFA24_eotS =
			"\x4\xFFFF";
		private const string DFA24_eofS =
			"\x4\xFFFF";
		private const string DFA24_minS =
			"\x2\x5\x2\xFFFF";
		private const string DFA24_maxS =
			"\x2\x1A\x2\xFFFF";
		private const string DFA24_acceptS =
			"\x2\xFFFF\x1\x2\x1\x1";
		private const string DFA24_specialS =
			"\x4\xFFFF}>";
		private static readonly string[] DFA24_transitionS =
			{
				"\x1\x2\x14\xFFFF\x1\x1",
				"\x1\x2\x1\xFFFF\x2\x3\x9\xFFFF\x1\x3\x7\xFFFF\x1\x1",
				"",
				""
			};

		private static readonly short[] DFA24_eot = DFA.UnpackEncodedString(DFA24_eotS);
		private static readonly short[] DFA24_eof = DFA.UnpackEncodedString(DFA24_eofS);
		private static readonly char[] DFA24_min = DFA.UnpackEncodedStringToUnsignedChars(DFA24_minS);
		private static readonly char[] DFA24_max = DFA.UnpackEncodedStringToUnsignedChars(DFA24_maxS);
		private static readonly short[] DFA24_accept = DFA.UnpackEncodedString(DFA24_acceptS);
		private static readonly short[] DFA24_special = DFA.UnpackEncodedString(DFA24_specialS);
		private static readonly short[][] DFA24_transition;

		static DFA24()
		{
			int numStates = DFA24_transitionS.Length;
			DFA24_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA24_transition[i] = DFA.UnpackEncodedString(DFA24_transitionS[i]);
			}
		}

		public DFA24( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 24;
			this.eot = DFA24_eot;
			this.eof = DFA24_eof;
			this.min = DFA24_min;
			this.max = DFA24_max;
			this.accept = DFA24_accept;
			this.special = DFA24_special;
			this.transition = DFA24_transition;
		}

		public override string Description { get { return "()* loopback of 140:11: ( ( NEWLINE )+ a= stmt )*"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}


	#endregion DFA

	#region Follow sets
	private static class Follow
	{
		public static readonly BitSet _node_in_root85 = new BitSet(new ulong[]{0x204400002UL});
		public static readonly BitSet _NEWLINE_in_root90 = new BitSet(new ulong[]{0x204400002UL});
		public static readonly BitSet _func_def_in_node112 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _IDENT_in_type_name136 = new BitSet(new ulong[]{0x404000000002UL});
		public static readonly BitSet _46_in_type_name141 = new BitSet(new ulong[]{0x200400000UL});
		public static readonly BitSet _type_name_in_type_name147 = new BitSet(new ulong[]{0x1020000000000UL});
		public static readonly BitSet _41_in_type_name152 = new BitSet(new ulong[]{0x200400000UL});
		public static readonly BitSet _type_name_in_type_name156 = new BitSet(new ulong[]{0x1020000000000UL});
		public static readonly BitSet _48_in_type_name162 = new BitSet(new ulong[]{0x404000000002UL});
		public static readonly BitSet _38_in_type_name169 = new BitSet(new ulong[]{0x4000000002UL});
		public static readonly BitSet _Type_Tuple_in_type_name181 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _type_name_in_type_name186 = new BitSet(new ulong[]{0x200400008UL});
		public static readonly BitSet _type_name_in_func_def217 = new BitSet(new ulong[]{0x400000UL});
		public static readonly BitSet _IDENT_in_func_def221 = new BitSet(new ulong[]{0x401000000000UL});
		public static readonly BitSet _46_in_func_def224 = new BitSet(new ulong[]{0x400000UL});
		public static readonly BitSet _IDENT_in_func_def229 = new BitSet(new ulong[]{0x1000000400000UL});
		public static readonly BitSet _48_in_func_def235 = new BitSet(new ulong[]{0x1000000000UL});
		public static readonly BitSet _36_in_func_def239 = new BitSet(new ulong[]{0x400020415A6A00UL});
		public static readonly BitSet _expr_in_func_def244 = new BitSet(new ulong[]{0x22000000000UL});
		public static readonly BitSet _41_in_func_def249 = new BitSet(new ulong[]{0x400000415A6A00UL});
		public static readonly BitSet _expr_in_func_def253 = new BitSet(new ulong[]{0x400000UL});
		public static readonly BitSet _IDENT_in_func_def257 = new BitSet(new ulong[]{0x22000000000UL});
		public static readonly BitSet _37_in_func_def263 = new BitSet(new ulong[]{0x800000UL});
		public static readonly BitSet _stmt_block_in_func_def270 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _INDENT_in_stmt_block294 = new BitSet(new ulong[]{0x4000020UL});
		public static readonly BitSet _NEWLINE_in_stmt_block297 = new BitSet(new ulong[]{0x4040180UL});
		public static readonly BitSet _stmt_in_stmt_block302 = new BitSet(new ulong[]{0x4000020UL});
		public static readonly BitSet _NEWLINE_in_stmt_block308 = new BitSet(new ulong[]{0x4000020UL});
		public static readonly BitSet _DEDENT_in_stmt_block311 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _stmt_expr_in_stmt332 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _stmt_alloc_in_stmt_expr351 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _stmt_return_in_stmt_expr360 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _alloc_expr_in_stmt_alloc379 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _alloc_expr_auto_in_stmt_alloc388 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _Expr_Return_in_stmt_return406 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_stmt_return411 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _IDENT_in_ident434 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ident_in_ident_list458 = new BitSet(new ulong[]{0x20000000002UL});
		public static readonly BitSet _41_in_ident_list464 = new BitSet(new ulong[]{0x400000UL});
		public static readonly BitSet _ident_in_ident_list468 = new BitSet(new ulong[]{0x80020000000000UL});
		public static readonly BitSet _55_in_ident_list474 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _Expr_Alloc_in_alloc_expr493 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _type_name_in_alloc_expr497 = new BitSet(new ulong[]{0x400000UL});
		public static readonly BitSet _ident_in_alloc_expr501 = new BitSet(new ulong[]{0x400000415A6A08UL});
		public static readonly BitSet _expr_in_alloc_expr506 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _Expr_Alloc_Auto_in_alloc_expr_auto528 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _ident_in_alloc_expr_auto532 = new BitSet(new ulong[]{0x400000415A6A08UL});
		public static readonly BitSet _expr_in_alloc_expr_auto537 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _Expr_New_in_new_expr564 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _IDENT_in_new_expr568 = new BitSet(new ulong[]{0x400000415A6A00UL});
		public static readonly BitSet _expr_in_new_expr575 = new BitSet(new ulong[]{0x400000415A6A08UL});
		public static readonly BitSet _INDENT_in_block_expr600 = new BitSet(new ulong[]{0x4000020UL});
		public static readonly BitSet _NEWLINE_in_block_expr603 = new BitSet(new ulong[]{0x4040180UL});
		public static readonly BitSet _stmt_in_block_expr608 = new BitSet(new ulong[]{0x4000020UL});
		public static readonly BitSet _NEWLINE_in_block_expr614 = new BitSet(new ulong[]{0x4000020UL});
		public static readonly BitSet _DEDENT_in_block_expr617 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _Expr_Tuple_in_expr_tuple642 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_expr_tuple647 = new BitSet(new ulong[]{0x400000415A6A08UL});
		public static readonly BitSet _Expr_Match_Tuple_in_expr_match_tuple674 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _IDENT_in_expr_match_tuple679 = new BitSet(new ulong[]{0x400008UL});
		public static readonly BitSet _expr_in_expr_list707 = new BitSet(new ulong[]{0x400000415A6A02UL});
		public static readonly BitSet _Expr_Call_in_call_expr727 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_call_expr731 = new BitSet(new ulong[]{0x400000415A6A08UL});
		public static readonly BitSet _expr_list_in_call_expr735 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _Expr_Dict_in_dict_expr755 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_dict_expr759 = new BitSet(new ulong[]{0x400000415A6A00UL});
		public static readonly BitSet _expr_in_dict_expr763 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _expr_tuple_in_expr787 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _call_expr_in_expr797 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _dict_expr_in_expr807 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _Expr_Dot_in_expr816 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_expr820 = new BitSet(new ulong[]{0x400000UL});
		public static readonly BitSet _IDENT_in_expr824 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _Expr_Bin_in_expr834 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _set_in_expr838 = new BitSet(new ulong[]{0x400000415A6A00UL});
		public static readonly BitSet _expr_in_expr856 = new BitSet(new ulong[]{0x400000415A6A00UL});
		public static readonly BitSet _expr_in_expr860 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _Expr_Suffix_in_expr870 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _set_in_expr874 = new BitSet(new ulong[]{0x400000415A6A00UL});
		public static readonly BitSet _expr_in_expr884 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _Expr_Prefix_in_expr894 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _set_in_expr898 = new BitSet(new ulong[]{0x400000415A6A00UL});
		public static readonly BitSet _expr_in_expr916 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _set_in_expr927 = new BitSet(new ulong[]{0x2UL});
	}
	#endregion Follow sets
}

} // namespace  SugarCpp.Compiler 
