//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 SugarWalker.g 2013-04-21 00:01:44

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


	using System;
	using System.Collections;


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;
using Antlr.Runtime.Tree;
using RewriteRuleITokenStream = Antlr.Runtime.Tree.RewriteRuleTokenStream;

namespace  SugarCpp.Compiler 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class SugarWalker : Antlr.Runtime.Tree.TreeParser
{
	internal static readonly string[] tokenNames = new string[] {
		"<invalid>", "<EOR>", "<DOWN>", "<UP>", "Block", "DEDENT", "DOUBLE", "EXPONENT", "Expr_Alloc", "Expr_Bin", "Expr_Block", "Expr_Call", "Expr_Dict", "Expr_Dot", "Expr_New", "Func_Def", "IDENT", "INDENT", "INT", "Left_Bracket", "NEWLINE", "Right_Bracket", "Root", "SP", "STRING", "Stmt_For", "Stmt_If", "Stmt_While", "'!'", "'!='", "')'", "'*'", "'+'", "'++'", "','", "'-'", "'--'", "'/'", "';'", "'<'", "'<='", "'='", "'=='", "'>'", "'>='", "']'", "'else'", "'for'", "'if'", "'import'", "'new'", "'struct'", "'while'"
	};
	public const int EOF=-1;
	public const int T__28=28;
	public const int T__29=29;
	public const int T__30=30;
	public const int T__31=31;
	public const int T__32=32;
	public const int T__33=33;
	public const int T__34=34;
	public const int T__35=35;
	public const int T__36=36;
	public const int T__37=37;
	public const int T__38=38;
	public const int T__39=39;
	public const int T__40=40;
	public const int T__41=41;
	public const int T__42=42;
	public const int T__43=43;
	public const int T__44=44;
	public const int T__45=45;
	public const int T__46=46;
	public const int T__47=47;
	public const int T__48=48;
	public const int T__49=49;
	public const int T__50=50;
	public const int T__51=51;
	public const int T__52=52;
	public const int Block=4;
	public const int DEDENT=5;
	public const int DOUBLE=6;
	public const int EXPONENT=7;
	public const int Expr_Alloc=8;
	public const int Expr_Bin=9;
	public const int Expr_Block=10;
	public const int Expr_Call=11;
	public const int Expr_Dict=12;
	public const int Expr_Dot=13;
	public const int Expr_New=14;
	public const int Func_Def=15;
	public const int IDENT=16;
	public const int INDENT=17;
	public const int INT=18;
	public const int Left_Bracket=19;
	public const int NEWLINE=20;
	public const int Right_Bracket=21;
	public const int Root=22;
	public const int SP=23;
	public const int STRING=24;
	public const int Stmt_For=25;
	public const int Stmt_If=26;
	public const int Stmt_While=27;

	public SugarWalker(ITreeNodeStream input)
		: this(input, new RecognizerSharedState())
	{
	}
	public SugarWalker(ITreeNodeStream input, RecognizerSharedState state)
		: base(input, state)
	{
		OnCreated();
	}

	public override string[] TokenNames { get { return SugarWalker.tokenNames; } }
	public override string GrammarFileName { get { return "SugarWalker.g"; } }




	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	#region Rules
	partial void EnterRule_root();
	partial void LeaveRule_root();

	// $ANTLR start "root"
	// SugarWalker.g:22:8: public root returns [Root value] : (a= node )+ ;
	[GrammarRule("root")]
	public Root root()
	{
		EnterRule_root();
		EnterRule("root", 1);
		TraceIn("root", 1);
		Root value = default(Root);


		AstNode a = default(AstNode);


			value = new Root();

		try { DebugEnterRule(GrammarFileName, "root");
		DebugLocation(22, 1);
		try
		{
			// SugarWalker.g:27:2: ( (a= node )+ )
			DebugEnterAlt(1);
			// SugarWalker.g:27:4: (a= node )+
			{
			DebugLocation(27, 4);
			// SugarWalker.g:27:4: (a= node )+
			int cnt1=0;
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_0 = input.LA(1);

				if ((LA1_0==IDENT||LA1_0==49||LA1_0==51))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch (alt1)
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:27:5: a= node
					{
					DebugLocation(27, 7);
					PushFollow(Follow._node_in_root87);
					a=node();
					PopFollow();

					DebugLocation(27, 15);
					 value.List.Add(a); 

					}
					break;

				default:
					if (cnt1 >= 1)
						goto loop1;

					EarlyExitException eee1 = new EarlyExitException( 1, input );
					DebugRecognitionException(eee1);
					throw eee1;
				}
				cnt1++;
			}
			loop1:
				;

			} finally { DebugExitSubRule(1); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("root", 1);
			LeaveRule("root", 1);
			LeaveRule_root();
		}
		DebugLocation(28, 1);
		} finally { DebugExitRule(GrammarFileName, "root"); }
		return value;

	}
	// $ANTLR end "root"

	partial void EnterRule_node();
	partial void LeaveRule_node();

	// $ANTLR start "node"
	// SugarWalker.g:30:1: node returns [AstNode value] : (a= func_def |b= imports |c= struct );
	[GrammarRule("node")]
	private AstNode node()
	{
		EnterRule_node();
		EnterRule("node", 2);
		TraceIn("node", 2);
		AstNode value = default(AstNode);


		FuncDef a = default(FuncDef);
		Import b = default(Import);
		Struct c = default(Struct);

		try { DebugEnterRule(GrammarFileName, "node");
		DebugLocation(30, 1);
		try
		{
			// SugarWalker.g:31:2: (a= func_def |b= imports |c= struct )
			int alt2=3;
			try { DebugEnterDecision(2, false);
			switch (input.LA(1))
			{
			case IDENT:
				{
				alt2 = 1;
				}
				break;
			case 49:
				{
				alt2 = 2;
				}
				break;
			case 51:
				{
				alt2 = 3;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 2, 0, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(2); }
			switch (alt2)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:31:4: a= func_def
				{
				DebugLocation(31, 6);
				PushFollow(Follow._func_def_in_node111);
				a=func_def();
				PopFollow();

				DebugLocation(31, 17);
				 value = a; 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// SugarWalker.g:32:4: b= imports
				{
				DebugLocation(32, 6);
				PushFollow(Follow._imports_in_node122);
				b=imports();
				PopFollow();

				DebugLocation(32, 16);
				 value = b; 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// SugarWalker.g:33:4: c= struct
				{
				DebugLocation(33, 6);
				PushFollow(Follow._struct_in_node133);
				c=@struct();
				PopFollow();

				DebugLocation(33, 15);
				 value = c; 

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("node", 2);
			LeaveRule("node", 2);
			LeaveRule_node();
		}
		DebugLocation(34, 1);
		} finally { DebugExitRule(GrammarFileName, "node"); }
		return value;

	}
	// $ANTLR end "node"

	partial void EnterRule_imports();
	partial void LeaveRule_imports();

	// $ANTLR start "imports"
	// SugarWalker.g:36:1: imports returns [Import value] : 'import' (a= STRING )? ( INDENT ( ( NEWLINE )+ b= STRING )+ ( NEWLINE )* DEDENT )? ( NEWLINE )* ;
	[GrammarRule("imports")]
	private Import imports()
	{
		EnterRule_imports();
		EnterRule("imports", 3);
		TraceIn("imports", 3);
		Import value = default(Import);


		CommonTree a = default(CommonTree);
		CommonTree b = default(CommonTree);


			value = new Import();

		try { DebugEnterRule(GrammarFileName, "imports");
		DebugLocation(36, 1);
		try
		{
			// SugarWalker.g:41:2: ( 'import' (a= STRING )? ( INDENT ( ( NEWLINE )+ b= STRING )+ ( NEWLINE )* DEDENT )? ( NEWLINE )* )
			DebugEnterAlt(1);
			// SugarWalker.g:41:4: 'import' (a= STRING )? ( INDENT ( ( NEWLINE )+ b= STRING )+ ( NEWLINE )* DEDENT )? ( NEWLINE )*
			{
			DebugLocation(41, 4);
			Match(input,49,Follow._49_in_imports155); 
			DebugLocation(41, 13);
			// SugarWalker.g:41:13: (a= STRING )?
			int alt3=2;
			try { DebugEnterSubRule(3);
			try { DebugEnterDecision(3, false);
			int LA3_0 = input.LA(1);

			if ((LA3_0==STRING))
			{
				alt3 = 1;
			}
			} finally { DebugExitDecision(3); }
			switch (alt3)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:41:14: a= STRING
				{
				DebugLocation(41, 16);
				a=(CommonTree)Match(input,STRING,Follow._STRING_in_imports162); 
				DebugLocation(41, 25);
				 value.NameList.Add(a.Text); 

				}
				break;

			}
			} finally { DebugExitSubRule(3); }

			DebugLocation(42, 4);
			// SugarWalker.g:42:4: ( INDENT ( ( NEWLINE )+ b= STRING )+ ( NEWLINE )* DEDENT )?
			int alt7=2;
			try { DebugEnterSubRule(7);
			try { DebugEnterDecision(7, false);
			int LA7_0 = input.LA(1);

			if ((LA7_0==INDENT))
			{
				alt7 = 1;
			}
			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:42:5: INDENT ( ( NEWLINE )+ b= STRING )+ ( NEWLINE )* DEDENT
				{
				DebugLocation(42, 5);
				Match(input,INDENT,Follow._INDENT_in_imports172); 
				DebugLocation(42, 12);
				// SugarWalker.g:42:12: ( ( NEWLINE )+ b= STRING )+
				int cnt5=0;
				try { DebugEnterSubRule(5);
				while (true)
				{
					int alt5=2;
					try { DebugEnterDecision(5, false);
					try
					{
						alt5 = dfa5.Predict(input);
					}
					catch (NoViableAltException nvae)
					{
						DebugRecognitionException(nvae);
						throw;
					}
					} finally { DebugExitDecision(5); }
					switch (alt5)
					{
					case 1:
						DebugEnterAlt(1);
						// SugarWalker.g:42:13: ( NEWLINE )+ b= STRING
						{
						DebugLocation(42, 13);
						// SugarWalker.g:42:13: ( NEWLINE )+
						int cnt4=0;
						try { DebugEnterSubRule(4);
						while (true)
						{
							int alt4=2;
							try { DebugEnterDecision(4, false);
							int LA4_0 = input.LA(1);

							if ((LA4_0==NEWLINE))
							{
								alt4 = 1;
							}


							} finally { DebugExitDecision(4); }
							switch (alt4)
							{
							case 1:
								DebugEnterAlt(1);
								// SugarWalker.g:42:13: NEWLINE
								{
								DebugLocation(42, 13);
								Match(input,NEWLINE,Follow._NEWLINE_in_imports175); 

								}
								break;

							default:
								if (cnt4 >= 1)
									goto loop4;

								EarlyExitException eee4 = new EarlyExitException( 4, input );
								DebugRecognitionException(eee4);
								throw eee4;
							}
							cnt4++;
						}
						loop4:
							;

						} finally { DebugExitSubRule(4); }

						DebugLocation(42, 24);
						b=(CommonTree)Match(input,STRING,Follow._STRING_in_imports182); 
						DebugLocation(42, 33);
						 value.NameList.Add(b.Text); 

						}
						break;

					default:
						if (cnt5 >= 1)
							goto loop5;

						EarlyExitException eee5 = new EarlyExitException( 5, input );
						DebugRecognitionException(eee5);
						throw eee5;
					}
					cnt5++;
				}
				loop5:
					;

				} finally { DebugExitSubRule(5); }

				DebugLocation(42, 68);
				// SugarWalker.g:42:68: ( NEWLINE )*
				try { DebugEnterSubRule(6);
				while (true)
				{
					int alt6=2;
					try { DebugEnterDecision(6, false);
					int LA6_0 = input.LA(1);

					if ((LA6_0==NEWLINE))
					{
						alt6 = 1;
					}


					} finally { DebugExitDecision(6); }
					switch ( alt6 )
					{
					case 1:
						DebugEnterAlt(1);
						// SugarWalker.g:42:68: NEWLINE
						{
						DebugLocation(42, 68);
						Match(input,NEWLINE,Follow._NEWLINE_in_imports188); 

						}
						break;

					default:
						goto loop6;
					}
				}

				loop6:
					;

				} finally { DebugExitSubRule(6); }

				DebugLocation(42, 77);
				Match(input,DEDENT,Follow._DEDENT_in_imports191); 

				}
				break;

			}
			} finally { DebugExitSubRule(7); }

			DebugLocation(42, 86);
			// SugarWalker.g:42:86: ( NEWLINE )*
			try { DebugEnterSubRule(8);
			while (true)
			{
				int alt8=2;
				try { DebugEnterDecision(8, false);
				int LA8_0 = input.LA(1);

				if ((LA8_0==NEWLINE))
				{
					alt8 = 1;
				}


				} finally { DebugExitDecision(8); }
				switch ( alt8 )
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:42:86: NEWLINE
					{
					DebugLocation(42, 86);
					Match(input,NEWLINE,Follow._NEWLINE_in_imports195); 

					}
					break;

				default:
					goto loop8;
				}
			}

			loop8:
				;

			} finally { DebugExitSubRule(8); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("imports", 3);
			LeaveRule("imports", 3);
			LeaveRule_imports();
		}
		DebugLocation(43, 1);
		} finally { DebugExitRule(GrammarFileName, "imports"); }
		return value;

	}
	// $ANTLR end "imports"

	partial void EnterRule_struct();
	partial void LeaveRule_struct();

	// $ANTLR start "struct"
	// SugarWalker.g:45:1: struct returns [Struct value] : 'struct' a= IDENT ( INDENT ( ( NEWLINE )+ b= stmt )+ DEDENT ) ( NEWLINE )* ;
	[GrammarRule("struct")]
	private Struct @struct()
	{
		EnterRule_struct();
		EnterRule("struct", 4);
		TraceIn("struct", 4);
		Struct value = default(Struct);


		CommonTree a = default(CommonTree);
		Stmt b = default(Stmt);


			value = new Struct();

		try { DebugEnterRule(GrammarFileName, "struct");
		DebugLocation(45, 1);
		try
		{
			// SugarWalker.g:50:2: ( 'struct' a= IDENT ( INDENT ( ( NEWLINE )+ b= stmt )+ DEDENT ) ( NEWLINE )* )
			DebugEnterAlt(1);
			// SugarWalker.g:50:4: 'struct' a= IDENT ( INDENT ( ( NEWLINE )+ b= stmt )+ DEDENT ) ( NEWLINE )*
			{
			DebugLocation(50, 4);
			Match(input,51,Follow._51_in_struct216); 
			DebugLocation(50, 14);
			a=(CommonTree)Match(input,IDENT,Follow._IDENT_in_struct220); 
			DebugLocation(50, 21);
			 value.Name = a.Text; 
			DebugLocation(50, 47);
			// SugarWalker.g:50:47: ( INDENT ( ( NEWLINE )+ b= stmt )+ DEDENT )
			DebugEnterAlt(1);
			// SugarWalker.g:50:48: INDENT ( ( NEWLINE )+ b= stmt )+ DEDENT
			{
			DebugLocation(50, 48);
			Match(input,INDENT,Follow._INDENT_in_struct225); 
			DebugLocation(50, 55);
			// SugarWalker.g:50:55: ( ( NEWLINE )+ b= stmt )+
			int cnt10=0;
			try { DebugEnterSubRule(10);
			while (true)
			{
				int alt10=2;
				try { DebugEnterDecision(10, false);
				int LA10_0 = input.LA(1);

				if ((LA10_0==NEWLINE))
				{
					alt10 = 1;
				}


				} finally { DebugExitDecision(10); }
				switch (alt10)
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:50:56: ( NEWLINE )+ b= stmt
					{
					DebugLocation(50, 56);
					// SugarWalker.g:50:56: ( NEWLINE )+
					int cnt9=0;
					try { DebugEnterSubRule(9);
					while (true)
					{
						int alt9=2;
						try { DebugEnterDecision(9, false);
						int LA9_0 = input.LA(1);

						if ((LA9_0==NEWLINE))
						{
							alt9 = 1;
						}


						} finally { DebugExitDecision(9); }
						switch (alt9)
						{
						case 1:
							DebugEnterAlt(1);
							// SugarWalker.g:50:56: NEWLINE
							{
							DebugLocation(50, 56);
							Match(input,NEWLINE,Follow._NEWLINE_in_struct228); 

							}
							break;

						default:
							if (cnt9 >= 1)
								goto loop9;

							EarlyExitException eee9 = new EarlyExitException( 9, input );
							DebugRecognitionException(eee9);
							throw eee9;
						}
						cnt9++;
					}
					loop9:
						;

					} finally { DebugExitSubRule(9); }

					DebugLocation(50, 66);
					PushFollow(Follow._stmt_in_struct233);
					b=stmt();
					PopFollow();

					DebugLocation(50, 72);
					 value.List.Add(b); 

					}
					break;

				default:
					if (cnt10 >= 1)
						goto loop10;

					EarlyExitException eee10 = new EarlyExitException( 10, input );
					DebugRecognitionException(eee10);
					throw eee10;
				}
				cnt10++;
			}
			loop10:
				;

			} finally { DebugExitSubRule(10); }

			DebugLocation(50, 99);
			Match(input,DEDENT,Follow._DEDENT_in_struct240); 

			}

			DebugLocation(50, 107);
			// SugarWalker.g:50:107: ( NEWLINE )*
			try { DebugEnterSubRule(11);
			while (true)
			{
				int alt11=2;
				try { DebugEnterDecision(11, false);
				int LA11_0 = input.LA(1);

				if ((LA11_0==NEWLINE))
				{
					alt11 = 1;
				}


				} finally { DebugExitDecision(11); }
				switch ( alt11 )
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:50:107: NEWLINE
					{
					DebugLocation(50, 107);
					Match(input,NEWLINE,Follow._NEWLINE_in_struct243); 

					}
					break;

				default:
					goto loop11;
				}
			}

			loop11:
				;

			} finally { DebugExitSubRule(11); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("struct", 4);
			LeaveRule("struct", 4);
			LeaveRule_struct();
		}
		DebugLocation(51, 1);
		} finally { DebugExitRule(GrammarFileName, "struct"); }
		return value;

	}
	// $ANTLR end "struct"

	partial void EnterRule_type_name();
	partial void LeaveRule_type_name();

	// $ANTLR start "type_name"
	// SugarWalker.g:53:1: type_name returns [string value] : a= IDENT ( '[' ']' )* ;
	[GrammarRule("type_name")]
	private string type_name()
	{
		EnterRule_type_name();
		EnterRule("type_name", 5);
		TraceIn("type_name", 5);
		string value = default(string);


		CommonTree a = default(CommonTree);


			value = "";

		try { DebugEnterRule(GrammarFileName, "type_name");
		DebugLocation(53, 1);
		try
		{
			// SugarWalker.g:58:2: (a= IDENT ( '[' ']' )* )
			DebugEnterAlt(1);
			// SugarWalker.g:58:4: a= IDENT ( '[' ']' )*
			{
			DebugLocation(58, 5);
			a=(CommonTree)Match(input,IDENT,Follow._IDENT_in_type_name266); 
			DebugLocation(58, 12);
			 value+=a; 
			DebugLocation(58, 27);
			// SugarWalker.g:58:27: ( '[' ']' )*
			try { DebugEnterSubRule(12);
			while (true)
			{
				int alt12=2;
				try { DebugEnterDecision(12, false);
				int LA12_0 = input.LA(1);

				if ((LA12_0==Expr_Dict))
				{
					alt12 = 1;
				}


				} finally { DebugExitDecision(12); }
				switch ( alt12 )
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:58:28: '[' ']'
					{
					DebugLocation(58, 28);
					Match(input,Expr_Dict,Follow._Expr_Dict_in_type_name271); 
					DebugLocation(58, 32);
					Match(input,45,Follow._45_in_type_name273); 
					DebugLocation(58, 36);
					 value+="*"; 

					}
					break;

				default:
					goto loop12;
				}
			}

			loop12:
				;

			} finally { DebugExitSubRule(12); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("type_name", 5);
			LeaveRule("type_name", 5);
			LeaveRule_type_name();
		}
		DebugLocation(59, 1);
		} finally { DebugExitRule(GrammarFileName, "type_name"); }
		return value;

	}
	// $ANTLR end "type_name"

	partial void EnterRule_func_def();
	partial void LeaveRule_func_def();

	// $ANTLR start "func_def"
	// SugarWalker.g:61:1: func_def returns [FuncDef value] : a= type_name b= IDENT '(' (c= expr ( ',' d= expr IDENT )* )? ')' e= stmt_block ( NEWLINE )* ;
	[GrammarRule("func_def")]
	private FuncDef func_def()
	{
		EnterRule_func_def();
		EnterRule("func_def", 6);
		TraceIn("func_def", 6);
		FuncDef value = default(FuncDef);


		CommonTree b = default(CommonTree);
		string a = default(string);
		Expr c = default(Expr);
		Expr d = default(Expr);
		StmtBlock e = default(StmtBlock);


			value = new FuncDef();

		try { DebugEnterRule(GrammarFileName, "func_def");
		DebugLocation(61, 1);
		try
		{
			// SugarWalker.g:66:2: (a= type_name b= IDENT '(' (c= expr ( ',' d= expr IDENT )* )? ')' e= stmt_block ( NEWLINE )* )
			DebugEnterAlt(1);
			// SugarWalker.g:66:4: a= type_name b= IDENT '(' (c= expr ( ',' d= expr IDENT )* )? ')' e= stmt_block ( NEWLINE )*
			{
			DebugLocation(66, 5);
			PushFollow(Follow._type_name_in_func_def299);
			a=type_name();
			PopFollow();

			DebugLocation(66, 17);
			b=(CommonTree)Match(input,IDENT,Follow._IDENT_in_func_def303); 
			DebugLocation(66, 24);
			Match(input,Expr_Call,Follow._Expr_Call_in_func_def305); 
			DebugLocation(66, 28);
			// SugarWalker.g:66:28: (c= expr ( ',' d= expr IDENT )* )?
			int alt14=2;
			try { DebugEnterSubRule(14);
			try { DebugEnterDecision(14, false);
			int LA14_0 = input.LA(1);

			if ((LA14_0==DOUBLE||LA14_0==Expr_Alloc||(LA14_0>=Expr_Call && LA14_0<=Expr_New)||LA14_0==IDENT||LA14_0==INT||LA14_0==STRING||(LA14_0>=28 && LA14_0<=29)||(LA14_0>=31 && LA14_0<=32)||LA14_0==35||LA14_0==37||(LA14_0>=39 && LA14_0<=44)))
			{
				alt14 = 1;
			}
			} finally { DebugExitDecision(14); }
			switch (alt14)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:66:29: c= expr ( ',' d= expr IDENT )*
				{
				DebugLocation(66, 30);
				PushFollow(Follow._expr_in_func_def310);
				c=expr();
				PopFollow();

				DebugLocation(66, 36);
				 value.Args.Add(c); 
				DebugLocation(66, 60);
				// SugarWalker.g:66:60: ( ',' d= expr IDENT )*
				try { DebugEnterSubRule(13);
				while (true)
				{
					int alt13=2;
					try { DebugEnterDecision(13, false);
					int LA13_0 = input.LA(1);

					if ((LA13_0==34))
					{
						alt13 = 1;
					}


					} finally { DebugExitDecision(13); }
					switch ( alt13 )
					{
					case 1:
						DebugEnterAlt(1);
						// SugarWalker.g:66:61: ',' d= expr IDENT
						{
						DebugLocation(66, 61);
						Match(input,34,Follow._34_in_func_def315); 
						DebugLocation(66, 66);
						PushFollow(Follow._expr_in_func_def319);
						d=expr();
						PopFollow();

						DebugLocation(66, 72);
						 value.Args.Add(d); 
						DebugLocation(66, 96);
						Match(input,IDENT,Follow._IDENT_in_func_def323); 

						}
						break;

					default:
						goto loop13;
					}
				}

				loop13:
					;

				} finally { DebugExitSubRule(13); }


				}
				break;

			}
			} finally { DebugExitSubRule(14); }

			DebugLocation(66, 106);
			Match(input,30,Follow._30_in_func_def329); 
			DebugLocation(66, 111);
			PushFollow(Follow._stmt_block_in_func_def333);
			e=stmt_block();
			PopFollow();

			DebugLocation(66, 123);
			// SugarWalker.g:66:123: ( NEWLINE )*
			try { DebugEnterSubRule(15);
			while (true)
			{
				int alt15=2;
				try { DebugEnterDecision(15, false);
				int LA15_0 = input.LA(1);

				if ((LA15_0==NEWLINE))
				{
					alt15 = 1;
				}


				} finally { DebugExitDecision(15); }
				switch ( alt15 )
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:66:123: NEWLINE
					{
					DebugLocation(66, 123);
					Match(input,NEWLINE,Follow._NEWLINE_in_func_def335); 

					}
					break;

				default:
					goto loop15;
				}
			}

			loop15:
				;

			} finally { DebugExitSubRule(15); }

			DebugLocation(67, 2);

					value.Type = a;
					value.Name = b.Text;
					value.Body = e;
				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("func_def", 6);
			LeaveRule("func_def", 6);
			LeaveRule_func_def();
		}
		DebugLocation(72, 1);
		} finally { DebugExitRule(GrammarFileName, "func_def"); }
		return value;

	}
	// $ANTLR end "func_def"

	partial void EnterRule_stmt_block();
	partial void LeaveRule_stmt_block();

	// $ANTLR start "stmt_block"
	// SugarWalker.g:74:1: stmt_block returns [StmtBlock value] : INDENT ( ( NEWLINE )+ a= stmt )* ( NEWLINE )* DEDENT ;
	[GrammarRule("stmt_block")]
	private StmtBlock stmt_block()
	{
		EnterRule_stmt_block();
		EnterRule("stmt_block", 7);
		TraceIn("stmt_block", 7);
		StmtBlock value = default(StmtBlock);


		Stmt a = default(Stmt);


			value = new StmtBlock();

		try { DebugEnterRule(GrammarFileName, "stmt_block");
		DebugLocation(74, 4);
		try
		{
			// SugarWalker.g:79:2: ( INDENT ( ( NEWLINE )+ a= stmt )* ( NEWLINE )* DEDENT )
			DebugEnterAlt(1);
			// SugarWalker.g:79:4: INDENT ( ( NEWLINE )+ a= stmt )* ( NEWLINE )* DEDENT
			{
			DebugLocation(79, 4);
			Match(input,INDENT,Follow._INDENT_in_stmt_block359); 
			DebugLocation(79, 11);
			// SugarWalker.g:79:11: ( ( NEWLINE )+ a= stmt )*
			try { DebugEnterSubRule(17);
			while (true)
			{
				int alt17=2;
				try { DebugEnterDecision(17, false);
				try
				{
					alt17 = dfa17.Predict(input);
				}
				catch (NoViableAltException nvae)
				{
					DebugRecognitionException(nvae);
					throw;
				}
				} finally { DebugExitDecision(17); }
				switch ( alt17 )
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:79:12: ( NEWLINE )+ a= stmt
					{
					DebugLocation(79, 12);
					// SugarWalker.g:79:12: ( NEWLINE )+
					int cnt16=0;
					try { DebugEnterSubRule(16);
					while (true)
					{
						int alt16=2;
						try { DebugEnterDecision(16, false);
						int LA16_0 = input.LA(1);

						if ((LA16_0==NEWLINE))
						{
							alt16 = 1;
						}


						} finally { DebugExitDecision(16); }
						switch (alt16)
						{
						case 1:
							DebugEnterAlt(1);
							// SugarWalker.g:79:12: NEWLINE
							{
							DebugLocation(79, 12);
							Match(input,NEWLINE,Follow._NEWLINE_in_stmt_block362); 

							}
							break;

						default:
							if (cnt16 >= 1)
								goto loop16;

							EarlyExitException eee16 = new EarlyExitException( 16, input );
							DebugRecognitionException(eee16);
							throw eee16;
						}
						cnt16++;
					}
					loop16:
						;

					} finally { DebugExitSubRule(16); }

					DebugLocation(79, 22);
					PushFollow(Follow._stmt_in_stmt_block367);
					a=stmt();
					PopFollow();

					DebugLocation(79, 28);
					 value.StmtList.Add(a); 

					}
					break;

				default:
					goto loop17;
				}
			}

			loop17:
				;

			} finally { DebugExitSubRule(17); }

			DebugLocation(79, 58);
			// SugarWalker.g:79:58: ( NEWLINE )*
			try { DebugEnterSubRule(18);
			while (true)
			{
				int alt18=2;
				try { DebugEnterDecision(18, false);
				int LA18_0 = input.LA(1);

				if ((LA18_0==NEWLINE))
				{
					alt18 = 1;
				}


				} finally { DebugExitDecision(18); }
				switch ( alt18 )
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:79:58: NEWLINE
					{
					DebugLocation(79, 58);
					Match(input,NEWLINE,Follow._NEWLINE_in_stmt_block373); 

					}
					break;

				default:
					goto loop18;
				}
			}

			loop18:
				;

			} finally { DebugExitSubRule(18); }

			DebugLocation(79, 67);
			Match(input,DEDENT,Follow._DEDENT_in_stmt_block376); 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("stmt_block", 7);
			LeaveRule("stmt_block", 7);
			LeaveRule_stmt_block();
		}
		DebugLocation(80, 4);
		} finally { DebugExitRule(GrammarFileName, "stmt_block"); }
		return value;

	}
	// $ANTLR end "stmt_block"

	partial void EnterRule_stmt();
	partial void LeaveRule_stmt();

	// $ANTLR start "stmt"
	// SugarWalker.g:82:1: stmt returns [Stmt value] : (a= expr |b= stmt_if |c= stmt_while |d= stmt_for );
	[GrammarRule("stmt")]
	private Stmt stmt()
	{
		EnterRule_stmt();
		EnterRule("stmt", 8);
		TraceIn("stmt", 8);
		Stmt value = default(Stmt);


		Expr a = default(Expr);
		StmtIf b = default(StmtIf);
		StmtWhile c = default(StmtWhile);
		StmtFor d = default(StmtFor);

		try { DebugEnterRule(GrammarFileName, "stmt");
		DebugLocation(82, 1);
		try
		{
			// SugarWalker.g:83:2: (a= expr |b= stmt_if |c= stmt_while |d= stmt_for )
			int alt19=4;
			try { DebugEnterDecision(19, false);
			switch (input.LA(1))
			{
			case DOUBLE:
			case Expr_Alloc:
			case Expr_Call:
			case Expr_Dict:
			case Expr_Dot:
			case Expr_New:
			case IDENT:
			case INT:
			case STRING:
			case 28:
			case 29:
			case 31:
			case 32:
			case 35:
			case 37:
			case 39:
			case 40:
			case 41:
			case 42:
			case 43:
			case 44:
				{
				alt19 = 1;
				}
				break;
			case 48:
				{
				alt19 = 2;
				}
				break;
			case 52:
				{
				alt19 = 3;
				}
				break;
			case 47:
				{
				alt19 = 4;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 19, 0, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(19); }
			switch (alt19)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:83:4: a= expr
				{
				DebugLocation(83, 5);
				PushFollow(Follow._expr_in_stmt397);
				a=expr();
				PopFollow();

				DebugLocation(83, 11);
				 value = a; 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// SugarWalker.g:84:4: b= stmt_if
				{
				DebugLocation(84, 5);
				PushFollow(Follow._stmt_if_in_stmt406);
				b=stmt_if();
				PopFollow();

				DebugLocation(84, 14);
				 value = b; 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// SugarWalker.g:85:4: c= stmt_while
				{
				DebugLocation(85, 5);
				PushFollow(Follow._stmt_while_in_stmt415);
				c=stmt_while();
				PopFollow();

				DebugLocation(85, 17);
				 value = c; 

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// SugarWalker.g:86:4: d= stmt_for
				{
				DebugLocation(86, 5);
				PushFollow(Follow._stmt_for_in_stmt424);
				d=stmt_for();
				PopFollow();

				DebugLocation(86, 15);
				 value = d; 

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("stmt", 8);
			LeaveRule("stmt", 8);
			LeaveRule_stmt();
		}
		DebugLocation(87, 1);
		} finally { DebugExitRule(GrammarFileName, "stmt"); }
		return value;

	}
	// $ANTLR end "stmt"

	partial void EnterRule_stmt_if();
	partial void LeaveRule_stmt_if();

	// $ANTLR start "stmt_if"
	// SugarWalker.g:89:1: stmt_if returns [StmtIf value] : 'if' a= expr b= stmt_block ( ( NEWLINE )* 'else' c= stmt_block )? ;
	[GrammarRule("stmt_if")]
	private StmtIf stmt_if()
	{
		EnterRule_stmt_if();
		EnterRule("stmt_if", 9);
		TraceIn("stmt_if", 9);
		StmtIf value = default(StmtIf);


		Expr a = default(Expr);
		StmtBlock b = default(StmtBlock);
		StmtBlock c = default(StmtBlock);

		try { DebugEnterRule(GrammarFileName, "stmt_if");
		DebugLocation(89, 1);
		try
		{
			// SugarWalker.g:90:2: ( 'if' a= expr b= stmt_block ( ( NEWLINE )* 'else' c= stmt_block )? )
			DebugEnterAlt(1);
			// SugarWalker.g:90:4: 'if' a= expr b= stmt_block ( ( NEWLINE )* 'else' c= stmt_block )?
			{
			DebugLocation(90, 4);
			Match(input,48,Follow._48_in_stmt_if442); 
			DebugLocation(90, 10);
			PushFollow(Follow._expr_in_stmt_if446);
			a=expr();
			PopFollow();

			DebugLocation(90, 17);
			PushFollow(Follow._stmt_block_in_stmt_if450);
			b=stmt_block();
			PopFollow();

			DebugLocation(90, 29);
			// SugarWalker.g:90:29: ( ( NEWLINE )* 'else' c= stmt_block )?
			int alt21=2;
			try { DebugEnterSubRule(21);
			try { DebugEnterDecision(21, false);
			try
			{
				alt21 = dfa21.Predict(input);
			}
			catch (NoViableAltException nvae)
			{
				DebugRecognitionException(nvae);
				throw;
			}
			} finally { DebugExitDecision(21); }
			switch (alt21)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:90:30: ( NEWLINE )* 'else' c= stmt_block
				{
				DebugLocation(90, 30);
				// SugarWalker.g:90:30: ( NEWLINE )*
				try { DebugEnterSubRule(20);
				while (true)
				{
					int alt20=2;
					try { DebugEnterDecision(20, false);
					int LA20_0 = input.LA(1);

					if ((LA20_0==NEWLINE))
					{
						alt20 = 1;
					}


					} finally { DebugExitDecision(20); }
					switch ( alt20 )
					{
					case 1:
						DebugEnterAlt(1);
						// SugarWalker.g:90:30: NEWLINE
						{
						DebugLocation(90, 30);
						Match(input,NEWLINE,Follow._NEWLINE_in_stmt_if453); 

						}
						break;

					default:
						goto loop20;
					}
				}

				loop20:
					;

				} finally { DebugExitSubRule(20); }

				DebugLocation(90, 39);
				Match(input,46,Follow._46_in_stmt_if456); 
				DebugLocation(90, 47);
				PushFollow(Follow._stmt_block_in_stmt_if460);
				c=stmt_block();
				PopFollow();


				}
				break;

			}
			} finally { DebugExitSubRule(21); }

			DebugLocation(91, 2);

					value = new StmtIf();
					value.Condition = a;
					value.Body = b;
					value.Else = c;
				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("stmt_if", 9);
			LeaveRule("stmt_if", 9);
			LeaveRule_stmt_if();
		}
		DebugLocation(97, 1);
		} finally { DebugExitRule(GrammarFileName, "stmt_if"); }
		return value;

	}
	// $ANTLR end "stmt_if"

	partial void EnterRule_stmt_while();
	partial void LeaveRule_stmt_while();

	// $ANTLR start "stmt_while"
	// SugarWalker.g:99:1: stmt_while returns [StmtWhile value] : 'while' a= expr b= stmt_block ;
	[GrammarRule("stmt_while")]
	private StmtWhile stmt_while()
	{
		EnterRule_stmt_while();
		EnterRule("stmt_while", 10);
		TraceIn("stmt_while", 10);
		StmtWhile value = default(StmtWhile);


		Expr a = default(Expr);
		StmtBlock b = default(StmtBlock);

		try { DebugEnterRule(GrammarFileName, "stmt_while");
		DebugLocation(99, 1);
		try
		{
			// SugarWalker.g:100:2: ( 'while' a= expr b= stmt_block )
			DebugEnterAlt(1);
			// SugarWalker.g:100:4: 'while' a= expr b= stmt_block
			{
			DebugLocation(100, 4);
			Match(input,52,Follow._52_in_stmt_while480); 
			DebugLocation(100, 13);
			PushFollow(Follow._expr_in_stmt_while484);
			a=expr();
			PopFollow();

			DebugLocation(100, 20);
			PushFollow(Follow._stmt_block_in_stmt_while488);
			b=stmt_block();
			PopFollow();

			DebugLocation(101, 2);

					value = new StmtWhile();
					value.Condition = a;
					value.Body = b;
				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("stmt_while", 10);
			LeaveRule("stmt_while", 10);
			LeaveRule_stmt_while();
		}
		DebugLocation(106, 1);
		} finally { DebugExitRule(GrammarFileName, "stmt_while"); }
		return value;

	}
	// $ANTLR end "stmt_while"

	partial void EnterRule_stmt_for();
	partial void LeaveRule_stmt_for();

	// $ANTLR start "stmt_for"
	// SugarWalker.g:108:1: stmt_for returns [StmtFor value] : 'for' '(' a= expr ';' b= expr ';' c= expr ')' d= stmt_block ;
	[GrammarRule("stmt_for")]
	private StmtFor stmt_for()
	{
		EnterRule_stmt_for();
		EnterRule("stmt_for", 11);
		TraceIn("stmt_for", 11);
		StmtFor value = default(StmtFor);


		Expr a = default(Expr);
		Expr b = default(Expr);
		Expr c = default(Expr);
		StmtBlock d = default(StmtBlock);

		try { DebugEnterRule(GrammarFileName, "stmt_for");
		DebugLocation(108, 1);
		try
		{
			// SugarWalker.g:109:2: ( 'for' '(' a= expr ';' b= expr ';' c= expr ')' d= stmt_block )
			DebugEnterAlt(1);
			// SugarWalker.g:109:4: 'for' '(' a= expr ';' b= expr ';' c= expr ')' d= stmt_block
			{
			DebugLocation(109, 4);
			Match(input,47,Follow._47_in_stmt_for506); 
			DebugLocation(109, 10);
			Match(input,Expr_Call,Follow._Expr_Call_in_stmt_for508); 
			DebugLocation(109, 15);
			PushFollow(Follow._expr_in_stmt_for512);
			a=expr();
			PopFollow();

			DebugLocation(109, 21);
			Match(input,38,Follow._38_in_stmt_for514); 
			DebugLocation(109, 26);
			PushFollow(Follow._expr_in_stmt_for518);
			b=expr();
			PopFollow();

			DebugLocation(109, 32);
			Match(input,38,Follow._38_in_stmt_for520); 
			DebugLocation(109, 37);
			PushFollow(Follow._expr_in_stmt_for524);
			c=expr();
			PopFollow();

			DebugLocation(109, 43);
			Match(input,30,Follow._30_in_stmt_for526); 
			DebugLocation(109, 48);
			PushFollow(Follow._stmt_block_in_stmt_for530);
			d=stmt_block();
			PopFollow();

			DebugLocation(110, 2);

					value = new StmtFor();
					value.Start = a;
					value.Condition = b;
					value.Next = c;
					value.Body = d;
				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("stmt_for", 11);
			LeaveRule("stmt_for", 11);
			LeaveRule_stmt_for();
		}
		DebugLocation(117, 1);
		} finally { DebugExitRule(GrammarFileName, "stmt_for"); }
		return value;

	}
	// $ANTLR end "stmt_for"

	partial void EnterRule_alloc_expr();
	partial void LeaveRule_alloc_expr();

	// $ANTLR start "alloc_expr"
	// SugarWalker.g:119:1: alloc_expr returns [ExprAlloc value] : ^( Expr_Alloc a= type_name b= IDENT (c= expr )? ) ;
	[GrammarRule("alloc_expr")]
	private ExprAlloc alloc_expr()
	{
		EnterRule_alloc_expr();
		EnterRule("alloc_expr", 12);
		TraceIn("alloc_expr", 12);
		ExprAlloc value = default(ExprAlloc);


		CommonTree b = default(CommonTree);
		string a = default(string);
		Expr c = default(Expr);

		try { DebugEnterRule(GrammarFileName, "alloc_expr");
		DebugLocation(119, 1);
		try
		{
			// SugarWalker.g:120:2: ( ^( Expr_Alloc a= type_name b= IDENT (c= expr )? ) )
			DebugEnterAlt(1);
			// SugarWalker.g:120:4: ^( Expr_Alloc a= type_name b= IDENT (c= expr )? )
			{
			DebugLocation(120, 4);
			DebugLocation(120, 6);
			Match(input,Expr_Alloc,Follow._Expr_Alloc_in_alloc_expr549); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(120, 18);
			PushFollow(Follow._type_name_in_alloc_expr553);
			a=type_name();
			PopFollow();

			DebugLocation(120, 30);
			b=(CommonTree)Match(input,IDENT,Follow._IDENT_in_alloc_expr557); 
			DebugLocation(120, 37);
			// SugarWalker.g:120:37: (c= expr )?
			int alt22=2;
			try { DebugEnterSubRule(22);
			try { DebugEnterDecision(22, false);
			int LA22_0 = input.LA(1);

			if ((LA22_0==DOUBLE||LA22_0==Expr_Alloc||(LA22_0>=Expr_Call && LA22_0<=Expr_New)||LA22_0==IDENT||LA22_0==INT||LA22_0==STRING||(LA22_0>=28 && LA22_0<=29)||(LA22_0>=31 && LA22_0<=32)||LA22_0==35||LA22_0==37||(LA22_0>=39 && LA22_0<=44)))
			{
				alt22 = 1;
			}
			} finally { DebugExitDecision(22); }
			switch (alt22)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:120:38: c= expr
				{
				DebugLocation(120, 39);
				PushFollow(Follow._expr_in_alloc_expr562);
				c=expr();
				PopFollow();


				}
				break;

			}
			} finally { DebugExitSubRule(22); }


			Match(input, TokenTypes.Up, null); 

			DebugLocation(121, 2);

					value = new ExprAlloc();
					value.Type = a;
					value.Name = b.Text;
					value.Expr = c;
				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("alloc_expr", 12);
			LeaveRule("alloc_expr", 12);
			LeaveRule_alloc_expr();
		}
		DebugLocation(127, 1);
		} finally { DebugExitRule(GrammarFileName, "alloc_expr"); }
		return value;

	}
	// $ANTLR end "alloc_expr"

	partial void EnterRule_args_list();
	partial void LeaveRule_args_list();

	// $ANTLR start "args_list"
	// SugarWalker.g:128:1: args_list returns [List<Expr> value] : (a= expr )* ;
	[GrammarRule("args_list")]
	private List<Expr> args_list()
	{
		EnterRule_args_list();
		EnterRule("args_list", 13);
		TraceIn("args_list", 13);
		List<Expr> value = default(List<Expr>);


		Expr a = default(Expr);


			value = new List<Expr>();

		try { DebugEnterRule(GrammarFileName, "args_list");
		DebugLocation(128, 1);
		try
		{
			// SugarWalker.g:133:2: ( (a= expr )* )
			DebugEnterAlt(1);
			// SugarWalker.g:133:4: (a= expr )*
			{
			DebugLocation(133, 4);
			// SugarWalker.g:133:4: (a= expr )*
			try { DebugEnterSubRule(23);
			while (true)
			{
				int alt23=2;
				try { DebugEnterDecision(23, false);
				int LA23_0 = input.LA(1);

				if ((LA23_0==DOUBLE||LA23_0==Expr_Alloc||(LA23_0>=Expr_Call && LA23_0<=Expr_New)||LA23_0==IDENT||LA23_0==INT||LA23_0==STRING||(LA23_0>=28 && LA23_0<=29)||(LA23_0>=31 && LA23_0<=32)||LA23_0==35||LA23_0==37||(LA23_0>=39 && LA23_0<=44)))
				{
					alt23 = 1;
				}


				} finally { DebugExitDecision(23); }
				switch ( alt23 )
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:133:5: a= expr
					{
					DebugLocation(133, 6);
					PushFollow(Follow._expr_in_args_list590);
					a=expr();
					PopFollow();

					DebugLocation(133, 12);
					 value.Add(a); 

					}
					break;

				default:
					goto loop23;
				}
			}

			loop23:
				;

			} finally { DebugExitSubRule(23); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("args_list", 13);
			LeaveRule("args_list", 13);
			LeaveRule_args_list();
		}
		DebugLocation(134, 1);
		} finally { DebugExitRule(GrammarFileName, "args_list"); }
		return value;

	}
	// $ANTLR end "args_list"

	partial void EnterRule_call_expr();
	partial void LeaveRule_call_expr();

	// $ANTLR start "call_expr"
	// SugarWalker.g:136:1: call_expr returns [Expr value] : ( ^( Expr_Call a= expr b= args_list ) | ^( Expr_Dict a= expr c= expr ) );
	[GrammarRule("call_expr")]
	private Expr call_expr()
	{
		EnterRule_call_expr();
		EnterRule("call_expr", 14);
		TraceIn("call_expr", 14);
		Expr value = default(Expr);


		Expr a = default(Expr);
		List<Expr> b = default(List<Expr>);
		Expr c = default(Expr);

		try { DebugEnterRule(GrammarFileName, "call_expr");
		DebugLocation(136, 1);
		try
		{
			// SugarWalker.g:137:2: ( ^( Expr_Call a= expr b= args_list ) | ^( Expr_Dict a= expr c= expr ) )
			int alt24=2;
			try { DebugEnterDecision(24, false);
			int LA24_0 = input.LA(1);

			if ((LA24_0==Expr_Call))
			{
				alt24 = 1;
			}
			else if ((LA24_0==Expr_Dict))
			{
				alt24 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 24, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(24); }
			switch (alt24)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:137:4: ^( Expr_Call a= expr b= args_list )
				{
				DebugLocation(137, 4);
				DebugLocation(137, 6);
				Match(input,Expr_Call,Follow._Expr_Call_in_call_expr610); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(137, 17);
				PushFollow(Follow._expr_in_call_expr614);
				a=expr();
				PopFollow();

				DebugLocation(137, 24);
				PushFollow(Follow._args_list_in_call_expr618);
				b=args_list();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(138, 2);

						value = new ExprCall(a, b);
					

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// SugarWalker.g:141:4: ^( Expr_Dict a= expr c= expr )
				{
				DebugLocation(141, 4);
				DebugLocation(141, 6);
				Match(input,Expr_Dict,Follow._Expr_Dict_in_call_expr628); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(141, 17);
				PushFollow(Follow._expr_in_call_expr632);
				a=expr();
				PopFollow();

				DebugLocation(141, 24);
				PushFollow(Follow._expr_in_call_expr636);
				c=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(142, 2);

						value = new ExprDict(a, c);
					

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("call_expr", 14);
			LeaveRule("call_expr", 14);
			LeaveRule_call_expr();
		}
		DebugLocation(145, 1);
		} finally { DebugExitRule(GrammarFileName, "call_expr"); }
		return value;

	}
	// $ANTLR end "call_expr"

	partial void EnterRule_dot_expr();
	partial void LeaveRule_dot_expr();

	// $ANTLR start "dot_expr"
	// SugarWalker.g:147:1: dot_expr returns [ExprDot value] : ^( Expr_Dot a= expr b= IDENT ) ;
	[GrammarRule("dot_expr")]
	private ExprDot dot_expr()
	{
		EnterRule_dot_expr();
		EnterRule("dot_expr", 15);
		TraceIn("dot_expr", 15);
		ExprDot value = default(ExprDot);


		CommonTree b = default(CommonTree);
		Expr a = default(Expr);

		try { DebugEnterRule(GrammarFileName, "dot_expr");
		DebugLocation(147, 1);
		try
		{
			// SugarWalker.g:148:2: ( ^( Expr_Dot a= expr b= IDENT ) )
			DebugEnterAlt(1);
			// SugarWalker.g:148:4: ^( Expr_Dot a= expr b= IDENT )
			{
			DebugLocation(148, 4);
			DebugLocation(148, 6);
			Match(input,Expr_Dot,Follow._Expr_Dot_in_dot_expr657); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(148, 16);
			PushFollow(Follow._expr_in_dot_expr661);
			a=expr();
			PopFollow();

			DebugLocation(148, 23);
			b=(CommonTree)Match(input,IDENT,Follow._IDENT_in_dot_expr665); 

			Match(input, TokenTypes.Up, null); 

			DebugLocation(149, 2);

					value = new ExprDot();
					value.Expr = a;
					value.Name = b.Text;
				

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("dot_expr", 15);
			LeaveRule("dot_expr", 15);
			LeaveRule_dot_expr();
		}
		DebugLocation(154, 1);
		} finally { DebugExitRule(GrammarFileName, "dot_expr"); }
		return value;

	}
	// $ANTLR end "dot_expr"

	partial void EnterRule_new_expr();
	partial void LeaveRule_new_expr();

	// $ANTLR start "new_expr"
	// SugarWalker.g:156:1: new_expr returns [ExprNew value] : ^( Expr_New a= IDENT (b= expr )+ ) ;
	[GrammarRule("new_expr")]
	private ExprNew new_expr()
	{
		EnterRule_new_expr();
		EnterRule("new_expr", 16);
		TraceIn("new_expr", 16);
		ExprNew value = default(ExprNew);


		CommonTree a = default(CommonTree);
		Expr b = default(Expr);


			value = new ExprNew();

		try { DebugEnterRule(GrammarFileName, "new_expr");
		DebugLocation(156, 1);
		try
		{
			// SugarWalker.g:161:2: ( ^( Expr_New a= IDENT (b= expr )+ ) )
			DebugEnterAlt(1);
			// SugarWalker.g:161:4: ^( Expr_New a= IDENT (b= expr )+ )
			{
			DebugLocation(161, 4);
			DebugLocation(161, 6);
			Match(input,Expr_New,Follow._Expr_New_in_new_expr690); 

			Match(input, TokenTypes.Down, null); 
			DebugLocation(161, 16);
			a=(CommonTree)Match(input,IDENT,Follow._IDENT_in_new_expr694); 
			DebugLocation(161, 23);
			 value.ElemType = a.Text; 
			DebugLocation(161, 53);
			// SugarWalker.g:161:53: (b= expr )+
			int cnt25=0;
			try { DebugEnterSubRule(25);
			while (true)
			{
				int alt25=2;
				try { DebugEnterDecision(25, false);
				int LA25_0 = input.LA(1);

				if ((LA25_0==DOUBLE||LA25_0==Expr_Alloc||(LA25_0>=Expr_Call && LA25_0<=Expr_New)||LA25_0==IDENT||LA25_0==INT||LA25_0==STRING||(LA25_0>=28 && LA25_0<=29)||(LA25_0>=31 && LA25_0<=32)||LA25_0==35||LA25_0==37||(LA25_0>=39 && LA25_0<=44)))
				{
					alt25 = 1;
				}


				} finally { DebugExitDecision(25); }
				switch (alt25)
				{
				case 1:
					DebugEnterAlt(1);
					// SugarWalker.g:161:54: b= expr
					{
					DebugLocation(161, 55);
					PushFollow(Follow._expr_in_new_expr701);
					b=expr();
					PopFollow();

					DebugLocation(161, 61);
					 value.Ranges.Add(b); 

					}
					break;

				default:
					if (cnt25 >= 1)
						goto loop25;

					EarlyExitException eee25 = new EarlyExitException( 25, input );
					DebugRecognitionException(eee25);
					throw eee25;
				}
				cnt25++;
			}
			loop25:
				;

			} finally { DebugExitSubRule(25); }


			Match(input, TokenTypes.Up, null); 


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("new_expr", 16);
			LeaveRule("new_expr", 16);
			LeaveRule_new_expr();
		}
		DebugLocation(162, 1);
		} finally { DebugExitRule(GrammarFileName, "new_expr"); }
		return value;

	}
	// $ANTLR end "new_expr"

	partial void EnterRule_expr();
	partial void LeaveRule_expr();

	// $ANTLR start "expr"
	// SugarWalker.g:164:1: expr returns [Expr value] : (alloc= alloc_expr |call= call_expr |dot= dot_expr |newExpr= new_expr | ^( '=' a= expr b= expr ) | ^( '+' a= expr b= expr ) | ^( '-' a= expr b= expr ) | ^( '*' a= expr b= expr ) | ^( '/' a= expr b= expr ) | ^( '==' a= expr b= expr ) | ^( '>' a= expr b= expr ) | ^( '>=' a= expr b= expr ) | ^( '<' a= expr b= expr ) | ^( '<=' a= expr b= expr ) | ^( '!=' a= expr b= expr ) | ^( '!' a= expr ) | INT | DOUBLE | IDENT | STRING );
	[GrammarRule("expr")]
	private Expr expr()
	{
		EnterRule_expr();
		EnterRule("expr", 17);
		TraceIn("expr", 17);
		Expr value = default(Expr);


		CommonTree INT1 = default(CommonTree);
		CommonTree DOUBLE2 = default(CommonTree);
		CommonTree IDENT3 = default(CommonTree);
		CommonTree STRING4 = default(CommonTree);
		ExprAlloc alloc = default(ExprAlloc);
		Expr call = default(Expr);
		ExprDot dot = default(ExprDot);
		ExprNew newExpr = default(ExprNew);
		Expr a = default(Expr);
		Expr b = default(Expr);

		try { DebugEnterRule(GrammarFileName, "expr");
		DebugLocation(164, 1);
		try
		{
			// SugarWalker.g:165:5: (alloc= alloc_expr |call= call_expr |dot= dot_expr |newExpr= new_expr | ^( '=' a= expr b= expr ) | ^( '+' a= expr b= expr ) | ^( '-' a= expr b= expr ) | ^( '*' a= expr b= expr ) | ^( '/' a= expr b= expr ) | ^( '==' a= expr b= expr ) | ^( '>' a= expr b= expr ) | ^( '>=' a= expr b= expr ) | ^( '<' a= expr b= expr ) | ^( '<=' a= expr b= expr ) | ^( '!=' a= expr b= expr ) | ^( '!' a= expr ) | INT | DOUBLE | IDENT | STRING )
			int alt26=20;
			try { DebugEnterDecision(26, false);
			switch (input.LA(1))
			{
			case Expr_Alloc:
				{
				alt26 = 1;
				}
				break;
			case Expr_Call:
			case Expr_Dict:
				{
				alt26 = 2;
				}
				break;
			case Expr_Dot:
				{
				alt26 = 3;
				}
				break;
			case Expr_New:
				{
				alt26 = 4;
				}
				break;
			case 41:
				{
				alt26 = 5;
				}
				break;
			case 32:
				{
				alt26 = 6;
				}
				break;
			case 35:
				{
				alt26 = 7;
				}
				break;
			case 31:
				{
				alt26 = 8;
				}
				break;
			case 37:
				{
				alt26 = 9;
				}
				break;
			case 42:
				{
				alt26 = 10;
				}
				break;
			case 43:
				{
				alt26 = 11;
				}
				break;
			case 44:
				{
				alt26 = 12;
				}
				break;
			case 39:
				{
				alt26 = 13;
				}
				break;
			case 40:
				{
				alt26 = 14;
				}
				break;
			case 29:
				{
				alt26 = 15;
				}
				break;
			case 28:
				{
				alt26 = 16;
				}
				break;
			case INT:
				{
				alt26 = 17;
				}
				break;
			case DOUBLE:
				{
				alt26 = 18;
				}
				break;
			case IDENT:
				{
				alt26 = 19;
				}
				break;
			case STRING:
				{
				alt26 = 20;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 26, 0, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(26); }
			switch (alt26)
			{
			case 1:
				DebugEnterAlt(1);
				// SugarWalker.g:165:7: alloc= alloc_expr
				{
				DebugLocation(165, 12);
				PushFollow(Follow._alloc_expr_in_expr726);
				alloc=alloc_expr();
				PopFollow();

				DebugLocation(166, 2);

						value = alloc;
					

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// SugarWalker.g:169:4: call= call_expr
				{
				DebugLocation(169, 8);
				PushFollow(Follow._call_expr_in_expr736);
				call=call_expr();
				PopFollow();

				DebugLocation(170, 2);

						value = call;
					

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// SugarWalker.g:173:4: dot= dot_expr
				{
				DebugLocation(173, 7);
				PushFollow(Follow._dot_expr_in_expr746);
				dot=dot_expr();
				PopFollow();

				DebugLocation(174, 2);

						value = dot;
					

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// SugarWalker.g:177:4: newExpr= new_expr
				{
				DebugLocation(177, 11);
				PushFollow(Follow._new_expr_in_expr756);
				newExpr=new_expr();
				PopFollow();

				DebugLocation(178, 2);

						value = newExpr;
					

				}
				break;
			case 5:
				DebugEnterAlt(5);
				// SugarWalker.g:181:4: ^( '=' a= expr b= expr )
				{
				DebugLocation(181, 4);
				DebugLocation(181, 6);
				Match(input,41,Follow._41_in_expr765); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(181, 11);
				PushFollow(Follow._expr_in_expr769);
				a=expr();
				PopFollow();

				DebugLocation(181, 18);
				PushFollow(Follow._expr_in_expr773);
				b=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(182, 2);

						value = new ExprAssign(a, b);
					

				}
				break;
			case 6:
				DebugEnterAlt(6);
				// SugarWalker.g:185:4: ^( '+' a= expr b= expr )
				{
				DebugLocation(185, 4);
				DebugLocation(185, 6);
				Match(input,32,Follow._32_in_expr783); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(185, 11);
				PushFollow(Follow._expr_in_expr787);
				a=expr();
				PopFollow();

				DebugLocation(185, 18);
				PushFollow(Follow._expr_in_expr791);
				b=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(186, 2);

						value = new ExprBin("+", a, b);
					

				}
				break;
			case 7:
				DebugEnterAlt(7);
				// SugarWalker.g:189:4: ^( '-' a= expr b= expr )
				{
				DebugLocation(189, 4);
				DebugLocation(189, 6);
				Match(input,35,Follow._35_in_expr801); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(189, 11);
				PushFollow(Follow._expr_in_expr805);
				a=expr();
				PopFollow();

				DebugLocation(189, 18);
				PushFollow(Follow._expr_in_expr809);
				b=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(190, 2);

						value = new ExprBin("-", a, b);
					

				}
				break;
			case 8:
				DebugEnterAlt(8);
				// SugarWalker.g:193:4: ^( '*' a= expr b= expr )
				{
				DebugLocation(193, 4);
				DebugLocation(193, 6);
				Match(input,31,Follow._31_in_expr819); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(193, 11);
				PushFollow(Follow._expr_in_expr823);
				a=expr();
				PopFollow();

				DebugLocation(193, 18);
				PushFollow(Follow._expr_in_expr827);
				b=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(194, 2);

						value = new ExprBin("*", a, b);
					

				}
				break;
			case 9:
				DebugEnterAlt(9);
				// SugarWalker.g:197:4: ^( '/' a= expr b= expr )
				{
				DebugLocation(197, 4);
				DebugLocation(197, 6);
				Match(input,37,Follow._37_in_expr837); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(197, 11);
				PushFollow(Follow._expr_in_expr841);
				a=expr();
				PopFollow();

				DebugLocation(197, 18);
				PushFollow(Follow._expr_in_expr845);
				b=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(198, 2);

						value = new ExprBin("/", a, b);
					

				}
				break;
			case 10:
				DebugEnterAlt(10);
				// SugarWalker.g:201:4: ^( '==' a= expr b= expr )
				{
				DebugLocation(201, 4);
				DebugLocation(201, 6);
				Match(input,42,Follow._42_in_expr855); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(201, 12);
				PushFollow(Follow._expr_in_expr859);
				a=expr();
				PopFollow();

				DebugLocation(201, 19);
				PushFollow(Follow._expr_in_expr863);
				b=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(202, 2);

						value = new ExprBin("==", a, b);
					

				}
				break;
			case 11:
				DebugEnterAlt(11);
				// SugarWalker.g:205:4: ^( '>' a= expr b= expr )
				{
				DebugLocation(205, 4);
				DebugLocation(205, 6);
				Match(input,43,Follow._43_in_expr873); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(205, 11);
				PushFollow(Follow._expr_in_expr877);
				a=expr();
				PopFollow();

				DebugLocation(205, 18);
				PushFollow(Follow._expr_in_expr881);
				b=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(206, 2);

						value = new ExprBin(">", a, b);
					

				}
				break;
			case 12:
				DebugEnterAlt(12);
				// SugarWalker.g:209:4: ^( '>=' a= expr b= expr )
				{
				DebugLocation(209, 4);
				DebugLocation(209, 6);
				Match(input,44,Follow._44_in_expr891); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(209, 12);
				PushFollow(Follow._expr_in_expr895);
				a=expr();
				PopFollow();

				DebugLocation(209, 19);
				PushFollow(Follow._expr_in_expr899);
				b=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(210, 2);

						value = new ExprBin(">=", a, b);
					

				}
				break;
			case 13:
				DebugEnterAlt(13);
				// SugarWalker.g:213:4: ^( '<' a= expr b= expr )
				{
				DebugLocation(213, 4);
				DebugLocation(213, 6);
				Match(input,39,Follow._39_in_expr909); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(213, 11);
				PushFollow(Follow._expr_in_expr913);
				a=expr();
				PopFollow();

				DebugLocation(213, 18);
				PushFollow(Follow._expr_in_expr917);
				b=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(214, 2);

						value = new ExprBin("<", a, b);
					

				}
				break;
			case 14:
				DebugEnterAlt(14);
				// SugarWalker.g:217:4: ^( '<=' a= expr b= expr )
				{
				DebugLocation(217, 4);
				DebugLocation(217, 6);
				Match(input,40,Follow._40_in_expr927); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(217, 12);
				PushFollow(Follow._expr_in_expr931);
				a=expr();
				PopFollow();

				DebugLocation(217, 19);
				PushFollow(Follow._expr_in_expr935);
				b=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(218, 2);

						value = new ExprBin("<=", a, b);
					

				}
				break;
			case 15:
				DebugEnterAlt(15);
				// SugarWalker.g:221:4: ^( '!=' a= expr b= expr )
				{
				DebugLocation(221, 4);
				DebugLocation(221, 6);
				Match(input,29,Follow._29_in_expr945); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(221, 12);
				PushFollow(Follow._expr_in_expr949);
				a=expr();
				PopFollow();

				DebugLocation(221, 19);
				PushFollow(Follow._expr_in_expr953);
				b=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(222, 2);

						value = new ExprBin("!=", a, b);
					

				}
				break;
			case 16:
				DebugEnterAlt(16);
				// SugarWalker.g:225:4: ^( '!' a= expr )
				{
				DebugLocation(225, 4);
				DebugLocation(225, 6);
				Match(input,28,Follow._28_in_expr963); 

				Match(input, TokenTypes.Down, null); 
				DebugLocation(225, 11);
				PushFollow(Follow._expr_in_expr967);
				a=expr();
				PopFollow();


				Match(input, TokenTypes.Up, null); 

				DebugLocation(226, 2);

						value = new ExprPrefix("!", a);
					

				}
				break;
			case 17:
				DebugEnterAlt(17);
				// SugarWalker.g:229:4: INT
				{
				DebugLocation(229, 4);
				INT1=(CommonTree)Match(input,INT,Follow._INT_in_expr976); 
				DebugLocation(230, 5);

				        value = new ExprConst(INT1.Text);
				    

				}
				break;
			case 18:
				DebugEnterAlt(18);
				// SugarWalker.g:233:4: DOUBLE
				{
				DebugLocation(233, 4);
				DOUBLE2=(CommonTree)Match(input,DOUBLE,Follow._DOUBLE_in_expr987); 
				DebugLocation(234, 2);

						value = new ExprConst(DOUBLE2.Text);
					

				}
				break;
			case 19:
				DebugEnterAlt(19);
				// SugarWalker.g:237:4: IDENT
				{
				DebugLocation(237, 4);
				IDENT3=(CommonTree)Match(input,IDENT,Follow._IDENT_in_expr995); 
				DebugLocation(238, 2);

						value = new ExprConst(IDENT3.Text);
					

				}
				break;
			case 20:
				DebugEnterAlt(20);
				// SugarWalker.g:241:4: STRING
				{
				DebugLocation(241, 4);
				STRING4=(CommonTree)Match(input,STRING,Follow._STRING_in_expr1003); 
				DebugLocation(242, 2);

						value = new ExprConst(STRING4.Text);
					

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("expr", 17);
			LeaveRule("expr", 17);
			LeaveRule_expr();
		}
		DebugLocation(245, 1);
		} finally { DebugExitRule(GrammarFileName, "expr"); }
		return value;

	}
	// $ANTLR end "expr"
	#endregion Rules


	#region DFA
	private DFA5 dfa5;
	private DFA17 dfa17;
	private DFA21 dfa21;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa5 = new DFA5( this );
		dfa17 = new DFA17( this );
		dfa21 = new DFA21( this );
	}

	private class DFA5 : DFA
	{
		private const string DFA5_eotS =
			"\x4\xFFFF";
		private const string DFA5_eofS =
			"\x4\xFFFF";
		private const string DFA5_minS =
			"\x2\x5\x2\xFFFF";
		private const string DFA5_maxS =
			"\x1\x14\x1\x18\x2\xFFFF";
		private const string DFA5_acceptS =
			"\x2\xFFFF\x1\x2\x1\x1";
		private const string DFA5_specialS =
			"\x4\xFFFF}>";
		private static readonly string[] DFA5_transitionS =
			{
				"\x1\x2\xE\xFFFF\x1\x1",
				"\x1\x2\xE\xFFFF\x1\x1\x3\xFFFF\x1\x3",
				"",
				""
			};

		private static readonly short[] DFA5_eot = DFA.UnpackEncodedString(DFA5_eotS);
		private static readonly short[] DFA5_eof = DFA.UnpackEncodedString(DFA5_eofS);
		private static readonly char[] DFA5_min = DFA.UnpackEncodedStringToUnsignedChars(DFA5_minS);
		private static readonly char[] DFA5_max = DFA.UnpackEncodedStringToUnsignedChars(DFA5_maxS);
		private static readonly short[] DFA5_accept = DFA.UnpackEncodedString(DFA5_acceptS);
		private static readonly short[] DFA5_special = DFA.UnpackEncodedString(DFA5_specialS);
		private static readonly short[][] DFA5_transition;

		static DFA5()
		{
			int numStates = DFA5_transitionS.Length;
			DFA5_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA5_transition[i] = DFA.UnpackEncodedString(DFA5_transitionS[i]);
			}
		}

		public DFA5( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 5;
			this.eot = DFA5_eot;
			this.eof = DFA5_eof;
			this.min = DFA5_min;
			this.max = DFA5_max;
			this.accept = DFA5_accept;
			this.special = DFA5_special;
			this.transition = DFA5_transition;
		}

		public override string Description { get { return "()+ loopback of 42:12: ( ( NEWLINE )+ b= STRING )+"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA17 : DFA
	{
		private const string DFA17_eotS =
			"\x4\xFFFF";
		private const string DFA17_eofS =
			"\x4\xFFFF";
		private const string DFA17_minS =
			"\x2\x5\x2\xFFFF";
		private const string DFA17_maxS =
			"\x1\x14\x1\x34\x2\xFFFF";
		private const string DFA17_acceptS =
			"\x2\xFFFF\x1\x2\x1\x1";
		private const string DFA17_specialS =
			"\x4\xFFFF}>";
		private static readonly string[] DFA17_transitionS =
			{
				"\x1\x2\xE\xFFFF\x1\x1",
				"\x1\x2\x1\x3\x1\xFFFF\x1\x3\x2\xFFFF\x4\x3\x1\xFFFF\x1\x3\x1\xFFFF"+
				"\x1\x3\x1\xFFFF\x1\x1\x3\xFFFF\x1\x3\x3\xFFFF\x2\x3\x1\xFFFF\x2\x3\x2"+
				"\xFFFF\x1\x3\x1\xFFFF\x1\x3\x1\xFFFF\x6\x3\x2\xFFFF\x2\x3\x3\xFFFF\x1"+
				"\x3",
				"",
				""
			};

		private static readonly short[] DFA17_eot = DFA.UnpackEncodedString(DFA17_eotS);
		private static readonly short[] DFA17_eof = DFA.UnpackEncodedString(DFA17_eofS);
		private static readonly char[] DFA17_min = DFA.UnpackEncodedStringToUnsignedChars(DFA17_minS);
		private static readonly char[] DFA17_max = DFA.UnpackEncodedStringToUnsignedChars(DFA17_maxS);
		private static readonly short[] DFA17_accept = DFA.UnpackEncodedString(DFA17_acceptS);
		private static readonly short[] DFA17_special = DFA.UnpackEncodedString(DFA17_specialS);
		private static readonly short[][] DFA17_transition;

		static DFA17()
		{
			int numStates = DFA17_transitionS.Length;
			DFA17_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA17_transition[i] = DFA.UnpackEncodedString(DFA17_transitionS[i]);
			}
		}

		public DFA17( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 17;
			this.eot = DFA17_eot;
			this.eof = DFA17_eof;
			this.min = DFA17_min;
			this.max = DFA17_max;
			this.accept = DFA17_accept;
			this.special = DFA17_special;
			this.transition = DFA17_transition;
		}

		public override string Description { get { return "()* loopback of 79:11: ( ( NEWLINE )+ a= stmt )*"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA21 : DFA
	{
		private const string DFA21_eotS =
			"\x4\xFFFF";
		private const string DFA21_eofS =
			"\x4\xFFFF";
		private const string DFA21_minS =
			"\x2\x5\x2\xFFFF";
		private const string DFA21_maxS =
			"\x1\x2E\x1\x34\x2\xFFFF";
		private const string DFA21_acceptS =
			"\x2\xFFFF\x1\x1\x1\x2";
		private const string DFA21_specialS =
			"\x4\xFFFF}>";
		private static readonly string[] DFA21_transitionS =
			{
				"\x1\x3\xE\xFFFF\x1\x1\x19\xFFFF\x1\x2",
				"\x2\x3\x1\xFFFF\x1\x3\x2\xFFFF\x4\x3\x1\xFFFF\x1\x3\x1\xFFFF\x1\x3"+
				"\x1\xFFFF\x1\x1\x3\xFFFF\x1\x3\x3\xFFFF\x2\x3\x1\xFFFF\x2\x3\x2\xFFFF"+
				"\x1\x3\x1\xFFFF\x1\x3\x1\xFFFF\x6\x3\x1\xFFFF\x1\x2\x2\x3\x3\xFFFF\x1"+
				"\x3",
				"",
				""
			};

		private static readonly short[] DFA21_eot = DFA.UnpackEncodedString(DFA21_eotS);
		private static readonly short[] DFA21_eof = DFA.UnpackEncodedString(DFA21_eofS);
		private static readonly char[] DFA21_min = DFA.UnpackEncodedStringToUnsignedChars(DFA21_minS);
		private static readonly char[] DFA21_max = DFA.UnpackEncodedStringToUnsignedChars(DFA21_maxS);
		private static readonly short[] DFA21_accept = DFA.UnpackEncodedString(DFA21_acceptS);
		private static readonly short[] DFA21_special = DFA.UnpackEncodedString(DFA21_specialS);
		private static readonly short[][] DFA21_transition;

		static DFA21()
		{
			int numStates = DFA21_transitionS.Length;
			DFA21_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA21_transition[i] = DFA.UnpackEncodedString(DFA21_transitionS[i]);
			}
		}

		public DFA21( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 21;
			this.eot = DFA21_eot;
			this.eof = DFA21_eof;
			this.min = DFA21_min;
			this.max = DFA21_max;
			this.accept = DFA21_accept;
			this.special = DFA21_special;
			this.transition = DFA21_transition;
		}

		public override string Description { get { return "90:29: ( ( NEWLINE )* 'else' c= stmt_block )?"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}


	#endregion DFA

	#region Follow sets
	private static class Follow
	{
		public static readonly BitSet _node_in_root87 = new BitSet(new ulong[]{0xA000000010002UL});
		public static readonly BitSet _func_def_in_node111 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _imports_in_node122 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _struct_in_node133 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _49_in_imports155 = new BitSet(new ulong[]{0x1120002UL});
		public static readonly BitSet _STRING_in_imports162 = new BitSet(new ulong[]{0x120002UL});
		public static readonly BitSet _INDENT_in_imports172 = new BitSet(new ulong[]{0x100000UL});
		public static readonly BitSet _NEWLINE_in_imports175 = new BitSet(new ulong[]{0x1100000UL});
		public static readonly BitSet _STRING_in_imports182 = new BitSet(new ulong[]{0x100020UL});
		public static readonly BitSet _NEWLINE_in_imports188 = new BitSet(new ulong[]{0x100020UL});
		public static readonly BitSet _DEDENT_in_imports191 = new BitSet(new ulong[]{0x100002UL});
		public static readonly BitSet _NEWLINE_in_imports195 = new BitSet(new ulong[]{0x100002UL});
		public static readonly BitSet _51_in_struct216 = new BitSet(new ulong[]{0x10000UL});
		public static readonly BitSet _IDENT_in_struct220 = new BitSet(new ulong[]{0x20000UL});
		public static readonly BitSet _INDENT_in_struct225 = new BitSet(new ulong[]{0x100000UL});
		public static readonly BitSet _NEWLINE_in_struct228 = new BitSet(new ulong[]{0x119FA9B1157940UL});
		public static readonly BitSet _stmt_in_struct233 = new BitSet(new ulong[]{0x100020UL});
		public static readonly BitSet _DEDENT_in_struct240 = new BitSet(new ulong[]{0x100002UL});
		public static readonly BitSet _NEWLINE_in_struct243 = new BitSet(new ulong[]{0x100002UL});
		public static readonly BitSet _IDENT_in_type_name266 = new BitSet(new ulong[]{0x1002UL});
		public static readonly BitSet _Expr_Dict_in_type_name271 = new BitSet(new ulong[]{0x200000000000UL});
		public static readonly BitSet _45_in_type_name273 = new BitSet(new ulong[]{0x1002UL});
		public static readonly BitSet _type_name_in_func_def299 = new BitSet(new ulong[]{0x10000UL});
		public static readonly BitSet _IDENT_in_func_def303 = new BitSet(new ulong[]{0x800UL});
		public static readonly BitSet _Expr_Call_in_func_def305 = new BitSet(new ulong[]{0x1FA9F1057940UL});
		public static readonly BitSet _expr_in_func_def310 = new BitSet(new ulong[]{0x440000000UL});
		public static readonly BitSet _34_in_func_def315 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_func_def319 = new BitSet(new ulong[]{0x10000UL});
		public static readonly BitSet _IDENT_in_func_def323 = new BitSet(new ulong[]{0x440000000UL});
		public static readonly BitSet _30_in_func_def329 = new BitSet(new ulong[]{0x20000UL});
		public static readonly BitSet _stmt_block_in_func_def333 = new BitSet(new ulong[]{0x100002UL});
		public static readonly BitSet _NEWLINE_in_func_def335 = new BitSet(new ulong[]{0x100002UL});
		public static readonly BitSet _INDENT_in_stmt_block359 = new BitSet(new ulong[]{0x100020UL});
		public static readonly BitSet _NEWLINE_in_stmt_block362 = new BitSet(new ulong[]{0x119FA9B1157940UL});
		public static readonly BitSet _stmt_in_stmt_block367 = new BitSet(new ulong[]{0x100020UL});
		public static readonly BitSet _NEWLINE_in_stmt_block373 = new BitSet(new ulong[]{0x100020UL});
		public static readonly BitSet _DEDENT_in_stmt_block376 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _expr_in_stmt397 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _stmt_if_in_stmt406 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _stmt_while_in_stmt415 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _stmt_for_in_stmt424 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _48_in_stmt_if442 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_stmt_if446 = new BitSet(new ulong[]{0x20000UL});
		public static readonly BitSet _stmt_block_in_stmt_if450 = new BitSet(new ulong[]{0x400000100002UL});
		public static readonly BitSet _NEWLINE_in_stmt_if453 = new BitSet(new ulong[]{0x400000100000UL});
		public static readonly BitSet _46_in_stmt_if456 = new BitSet(new ulong[]{0x20000UL});
		public static readonly BitSet _stmt_block_in_stmt_if460 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _52_in_stmt_while480 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_stmt_while484 = new BitSet(new ulong[]{0x20000UL});
		public static readonly BitSet _stmt_block_in_stmt_while488 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _47_in_stmt_for506 = new BitSet(new ulong[]{0x800UL});
		public static readonly BitSet _Expr_Call_in_stmt_for508 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_stmt_for512 = new BitSet(new ulong[]{0x4000000000UL});
		public static readonly BitSet _38_in_stmt_for514 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_stmt_for518 = new BitSet(new ulong[]{0x4000000000UL});
		public static readonly BitSet _38_in_stmt_for520 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_stmt_for524 = new BitSet(new ulong[]{0x40000000UL});
		public static readonly BitSet _30_in_stmt_for526 = new BitSet(new ulong[]{0x20000UL});
		public static readonly BitSet _stmt_block_in_stmt_for530 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _Expr_Alloc_in_alloc_expr549 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _type_name_in_alloc_expr553 = new BitSet(new ulong[]{0x10000UL});
		public static readonly BitSet _IDENT_in_alloc_expr557 = new BitSet(new ulong[]{0x1FA9B1057948UL});
		public static readonly BitSet _expr_in_alloc_expr562 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _expr_in_args_list590 = new BitSet(new ulong[]{0x1FA9B1057942UL});
		public static readonly BitSet _Expr_Call_in_call_expr610 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_call_expr614 = new BitSet(new ulong[]{0x1FA9B1057948UL});
		public static readonly BitSet _args_list_in_call_expr618 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _Expr_Dict_in_call_expr628 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_call_expr632 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_call_expr636 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _Expr_Dot_in_dot_expr657 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_dot_expr661 = new BitSet(new ulong[]{0x10000UL});
		public static readonly BitSet _IDENT_in_dot_expr665 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _Expr_New_in_new_expr690 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _IDENT_in_new_expr694 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_new_expr701 = new BitSet(new ulong[]{0x1FA9B1057948UL});
		public static readonly BitSet _alloc_expr_in_expr726 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _call_expr_in_expr736 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _dot_expr_in_expr746 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _new_expr_in_expr756 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _41_in_expr765 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_expr769 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_expr773 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _32_in_expr783 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_expr787 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_expr791 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _35_in_expr801 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_expr805 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_expr809 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _31_in_expr819 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_expr823 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_expr827 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _37_in_expr837 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_expr841 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_expr845 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _42_in_expr855 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_expr859 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_expr863 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _43_in_expr873 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_expr877 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_expr881 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _44_in_expr891 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_expr895 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_expr899 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _39_in_expr909 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_expr913 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_expr917 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _40_in_expr927 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_expr931 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_expr935 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _29_in_expr945 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_expr949 = new BitSet(new ulong[]{0x1FA9B1057940UL});
		public static readonly BitSet _expr_in_expr953 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _28_in_expr963 = new BitSet(new ulong[]{0x4UL});
		public static readonly BitSet _expr_in_expr967 = new BitSet(new ulong[]{0x8UL});
		public static readonly BitSet _INT_in_expr976 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _DOUBLE_in_expr987 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _IDENT_in_expr995 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _STRING_in_expr1003 = new BitSet(new ulong[]{0x2UL});
	}
	#endregion Follow sets
}

} // namespace  SugarCpp.Compiler 
